"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of schematic.kdl.
"""

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.hsplit(
            ui.tabs(
                ui.log_stream(
                    "fsw.log",
                    name="Flight Software Log",
                ),
                share=0.5,
            ),
            ui.vsplit(
                ui.tabs(
                    ui.viewport(
                        name="Viewport",
                        fov=45.0,
                        active=False,
                        show_grid=True,
                        show_arrows=True,
                        create_frustum=False,
                        show_frustums=False,
                        frustums_color="yellow",
                        projection_color="white",
                        frustums_thickness=0.006,
                        show_view_cube=True,
                        effects=True,
                        hdr=False,
                        cinematic=False,
                        pos="(0,0,0,0, 0,0,12)",
                        look_at="(0,0,0,0, 0,0,0)",
                        smoothing=0.0,
                    ),
                ),
                ui.graph(
                    "ball.wind",
                    name="Wind (m/s)",
                ),
                share=0.5,
            ),
        ),
        ui.object_3d(
            "ball.world_pos",
            mesh=ui.sphere(
                radius=0.3,
                color="orange",
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "(0,0,0,1, 0,0,0)",
            mesh=ui.plane(
                width=10.0,
                depth=10.0,
                color=ui.color(
                    32,
                    128,
                    32,
                    200,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.vector_arrow(
            "ball.wind",
            origin="(0,0,0,1, 0,0,0.5)",
            name="Wind",
            color=ui.color(
                0,
                255,
                255,
                200,
            ),
            scale=0.3,
            body_frame=False,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
