database_url = "postgresql://postgres:secret@postgres.elodin-app-dev.svc.cluster.local:5432/postgres"
redis_url = "redis://redis.elodin-app-dev.svc.cluster.local:6379"
migrate = false

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"

[api.stripe_plans]
monte_carlo_price = "price_1PBnS5G68UBhCjJFgvwkvQwx"
commercial_price = "price_1PBnNtG68UBhCjJF82vJsv5n"
non_commercial_price = "price_1PBnNDG68UBhCjJFLZMvrR92"

[monte_carlo]
sim_artifacts_bucket_name = "sim-artifacts-dev"
sim_results_bucket_name = "sim-results-dev"
