database_url = "postgresql://postgres:secret@postgres.elodin-app-dev.svc.cluster.local:5432/postgres"
redis_url = "redis://redis.elodin-app-dev.svc.cluster.local:6379"
migrate = false

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"

[api.stripe_plans.commercial]
monte_carlo_price = "price_1PtX1XG68UBhCjJFWfOr7ZBw"
subscription_price = "price_1PBnNtG68UBhCjJF82vJsv5n"
trial_length = 432000   # 5 days
monte_carlo_credit = 60000

[api.stripe_plans.non_commercial]
monte_carlo_price = "price_1PtX0TG68UBhCjJFYghysDOQ"
subscription_price = "price_1PBnNDG68UBhCjJFLZMvrR92"
trial_length = 2592000  # 30 days
monte_carlo_credit = 60

[monte_carlo]
sim_artifacts_bucket_name = "sim-artifacts-dev"
sim_results_bucket_name = "sim-results-dev"
