apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ../../modules/elo-docs/

patches:
- target:
    kind: Ingress
    name: elodin
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: app.elodin.dev
    - op: add
      path: /spec/rules/1
      value:
        host: docs.elodin.dev
        http:
          paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: elo-docs
                port: 
                  number: 80
- target:
    namespace: elodin-app
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: elodin-app-dev
- target:
    kind: Namespace
    name: elodin-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-app-dev
- target:
    kind: Namespace
    name: elodin-vms
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-vms-dev
- target:
    namespace: elodin-vms
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: elodin-vms-dev
- target:
    kind: RoleBinding
    name: elo-atc
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: elodin-app-dev
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: elo-atc
      annotations:
        iam.gke.io/gcp-service-account: sim-gcs@elodin-dev.iam.gserviceaccount.com
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: elo-sim-agent
      annotations:
        iam.gke.io/gcp-service-account: sim-gcs@elodin-dev.iam.gserviceaccount.com

configMapGenerator:
- name: elo-atc-config
  namespace: elodin-app
  files:
  - atc.toml=elo-atc-config.toml
- name: elo-atc-proxy-config
  namespace: elodin-app
  files:
  - atc.toml=elo-atc-proxy-config.toml
- name: elo-sim-config
  namespace: elodin-vms
  files:
  - sim.toml=elo-sim-config.toml
- name: elo-dashboard
  namespace: elodin-app
  literals:
  - PHX_HOST=app.elodin.dev
  - RELEASE_COOKIE=dummy_cookie
  - SECRET_KEY_BASE=pvS+BSCE9uyDsYR3d4A/vENpQj/0OtpzR+N/FAY1+yQD1OfS8Adp2nh537rzSEb0
  - ATC_INTERNAL_ADDR=elo-atc.elodin-app-dev.svc.cluster.local:50051
  - ATC_ADDR=app.elodin.dev
  - AUTH_BASE_URL=https://auth.elodin.dev

secretGenerator:
- name: elo-dashboard-secret
  namespace: elodin-app
  envs:
  - elo-dashboard-secret.env

replacements:
- source:
    kind: Deployment
    name: sim-agent-mc
    fieldPath: spec.template.spec.containers.[name=sim-agent-mc].image
  targets:
  - select:
      kind: Deployment
      name: elo-atc
    fieldPaths:
    - spec.template.spec.containers.[name=elo-atc].env.[name=ELODIN_ORCA.IMAGE_NAME].value

images:
- name: elodin-infra/elo-atc
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-atc/x86_64
  newTag: $BUILDKITE_COMMIT
- name: elodin-infra/elo-dashboard
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-dashboard/x86_64
  newTag: $BUILDKITE_COMMIT
- name: elodin-infra/elo-sim-agent
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-sim-agent/x86_64
  newTag: $BUILDKITE_COMMIT
- name: elodin-infra/elo-docs
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-docs/x86_64
  newTag: $BUILDKITE_COMMIT
