apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- stateful-set.yaml
- service.yaml

configMapGenerator:
- name: redis-config
  files:
  - redis.conf

labels:
- pairs:
    app: redis
  fields:
  - path: metadata/labels
    create: true
  - path: spec/selector
    create: true
    kind: Service
  - path: spec/selector/matchLabels
    create: true
    kind: StatefulSet
  - path: spec/template/metadata/labels
    create: true
    kind: StatefulSet
  - path: spec/selector/matchLabels
    create: true
    kind: PodDisruptionBudget
