apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: elo-docs
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml

namespace: elodin-app
