[package]
name = "editor-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paracosm.path = "../../libs/paracosm-core"
paracosm-editor.path = "../../libs/paracosm-editor"
ewebsock.version = "0.4"
ewebsock.features = ["tokio"]
bevy.version = "0.12"
postcard.version = "1.0.8"
postcard.features = ["alloc"]
anyhow = "1.0"
web-sys.version = "0.3.65"
web-sys.features = ["CustomEvent"]
wasm-bindgen = "0.2.88"
tracing = "0.1"
