target_dir := "../../target/wasm32-unknown-unknown/release"
out_dir := target_dir + "/editor-web"

build:
  rm -rf {{out_dir}}
  cargo build --release --target wasm32-unknown-unknown
  wasm-bindgen --out-dir {{out_dir}} --target web {{target_dir}}/editor-web.wasm
  mkdir -p ../../services/dashboard/priv/static/assets/wasm/
  cp {{out_dir}}/* ../../services/dashboard/priv/static/assets/wasm/
  cp {{out_dir}}/* ../../libs/nox-py/assets
  mkdir -p assets && cp {{out_dir}}/* ./assets/
