[package]
name = "sim-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
elodin-types = { version = "0.1.0", path = "../../libs/elodin-types/rust" }

tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
tokio-vsock = { git = "https://github.com/rust-vsock/tokio-vsock", rev = "44321de", features = ["tonic-conn"] }
tonic = { version = "0.11.0", features = ["zstd"] }
tonic-reflection = "0.11"
tonic-health = "0.11"
anyhow = "1.0.80"
tower = "0.4.13"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tempfile = "3.10.1"
tar = "0.4.40"
