[package]
name = "sim-builder"
version = "0.1.0"
edition = "2021"
metadata.dist.dist = false

[dependencies]
elodin-types = { version = "0.1.0", path = "../../libs/elodin-types/rust" }

tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
tonic = { version = "0.12.0" }
tonic-reflection = "0.12"
tonic-health = "0.12"
anyhow = "1.0.80"
tower = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tempfile = "3.10.1"
tar = "0.4.40"
uuid = { version = "1.6.1", features = ["v7"] }
tokio-util = "0.7"
blake3 = "1.5.1"

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = { git = "https://github.com/rust-vsock/tokio-vsock", rev = "3a41323", features = ["tonic-conn"] }

[dev-dependencies]
hyper-util.version = "0.1.6"
hyper-util.features = ["tokio"]
