#!/bin/sh

mount -n -t proc none /proc
mount -n -t sysfs none /sys
mount -n -t tmpfs none /tmp
export RUST_LOG="sim_builder=debug,info"
setsid /bin/sim-builder
# setsid sh -c 'sh </dev/ttyS0 >/dev/ttyS0 2>&1'
poweroff -f
