#!/bin/sh

hostname_cksum="$(hostname | tr -d '\n' | cksum | cut -d " " -f1)"
cid=${CID:-$hostname_cksum}
qemu-system-x86_64 \
    -machine microvm,rtc=on \
    -bios vm/bios.bin \
    -kernel vm/bzImage \
    -append 'console=ttyS0 quiet panic=-1 reboot=t root=/dev/vda init=/init raid=noautodetect ro' \
    -drive "file=vm/root.squashfs,format=raw,id=root,if=none,readonly=on" -device virtio-blk-device,drive=root \
    -device "vhost-vsock-device,id=vsock_id,guest-cid=$cid" \
    -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
    -cpu host \
    -m 1G \
    -accel kvm \
    -nographic \
    -no-reboot
