# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: component_broadcast.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'component_broadcast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63omponent_broadcast.proto\x12\x10\x65lodin.broadcast\"\xce\x01\n\x12\x43omponentBroadcast\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63omponent_name\x18\x02 \x01(\t\x12\x19\n\x11renamed_component\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x03\x12-\n\tdata_type\x18\x05 \x01(\x0e\x32\x1a.elodin.broadcast.PrimType\x12\r\n\x05shape\x18\x06 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12\x10\n\x08sequence\x18\x08 \x01(\x04\"l\n\x12\x42roadcastHeartbeat\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x12\n\ncomponents\x18\x02 \x03(\t\x12\x19\n\x11\x62roadcast_rate_hz\x18\x03 \x01(\x02\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x03*\xf5\x01\n\x08PrimType\x12\x19\n\x15PRIM_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0cPRIM_TYPE_U8\x10\x01\x12\x11\n\rPRIM_TYPE_U16\x10\x02\x12\x11\n\rPRIM_TYPE_U32\x10\x03\x12\x11\n\rPRIM_TYPE_U64\x10\x04\x12\x10\n\x0cPRIM_TYPE_I8\x10\x05\x12\x11\n\rPRIM_TYPE_I16\x10\x06\x12\x11\n\rPRIM_TYPE_I32\x10\x07\x12\x11\n\rPRIM_TYPE_I64\x10\x08\x12\x11\n\rPRIM_TYPE_F32\x10\t\x12\x11\n\rPRIM_TYPE_F64\x10\n\x12\x12\n\x0ePRIM_TYPE_BOOL\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component_broadcast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIMTYPE']._serialized_start=367
  _globals['_PRIMTYPE']._serialized_end=612
  _globals['_COMPONENTBROADCAST']._serialized_start=48
  _globals['_COMPONENTBROADCAST']._serialized_end=254
  _globals['_BROADCASTHEARTBEAT']._serialized_start=256
  _globals['_BROADCASTHEARTBEAT']._serialized_end=364
# @@protoc_insertion_point(module_scope)
