
[workspace]
members = [
  "cargo:.",
  "cargo:libs/db",
]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]
# Build only the required packages, and individually
precise-builds = true
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Whether to auto-include files like READMEs, LICENSEs, and CHANGELOGs (default true)
auto-includes = false
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-22.04-arm-large"
x86_64-unknown-linux-gnu = "ubuntu-22.04-xl"
aarch64-unknown-linux-musl = "ubuntu-22.04-arm-large"
x86_64-unknown-linux-musl = "ubuntu-22.04-xl"
x86_64-pc-windows-msvc = "windows-xl"
aarch64-apple-darwin = "macos-14-xlarge"

[dist.dependencies.apt]
"g++" = '*'
pkg-config = '*'
libx11-dev = '*'
libasound2-dev = '*'
libudev-dev = '*'
libxkbcommon-x11-0 = '*'
libwayland-dev = '*'
libxkbcommon-dev = '*'
gfortran = '*'
gfortran-12 = '*'
libgfortran-12-dev = '*'

[dist.dependencies.chocolatey]
cmake = '*'
