[project]
name = "elodin"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "elodin"
]

[tool.ruff]
line-length = 100
extend-exclude = ["vendor", "basilisk"]

[tool.ruff.lint]
extend-select = ["I"]
