[default.extend-words]
"UE" = "UE"
"SITL" = "SITL"
"NED" = "NED"
"ECI" = "ECI"
"ECEF" = "ECEF"
"thst" = "thst"
"hsi" = "hsi"
"thr" = "thr"
"som" = "som"
"lits" = "lits"
"ba" = "ba"
"datatime" = "datatime"
"struc" = "struc"
"LICENS" = "LICENS"
"aks" = "aks"
"ot" = "ot"
"fram" = "fram"
"FRAM" = "FRAM"
"THS" = "THS"
"LOD" = "LOD"
"lod" = "lod"
"ALOS" = "ALOS"
"bse" = "bse"
"numer" = "numer"
"ix" = "ix"
"iy" = "iy"
"iz" = "iz"
"PNGs" = "PNGs"
"PN" = "PN"
"FO" = "FO"

[files]
extend-exclude = [
    "**/target/*",
    "docs/public/static/js/*",
    "**/vendor/*",
    "pcbs/*",
    "/apps/unreal-demo/Plugins/RustPlugin",
    "*.dts",
    "images/orin-nano/flake.nix",
    "**/simulink/**/*.xml",
    "libs/stellarator/maitake",
    "aleph/modules/*.nix",
    "*.age",
    "examples/linalg/*",
    "libs/cranelift-mlir/*",
    "assets/terrains"
]
ignore-vcs = true
