"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of .ellipsoid.rendered.kdl.
"""

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.tabs(
            ui.hsplit(
                ui.viewport(
                    name="Viewport Source",
                    fov=45.0,
                    near=0.05,
                    far=6.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=True,
                    show_frustums=False,
                    frustums_color="yalk",
                    projection_color="mint",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="(0,0,0,1, -3,-0.5,2)",
                    look_at="(0,0,0,0, 0,0,0)",
                    smoothing=0.0,
                ),
                ui.viewport(
                    name="Target View",
                    fov=45.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=True,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="(0,0,0,1, 2,2,1.5)",
                    look_at="(0,0,0,0, 0,0,0)",
                    smoothing=0.0,
                ),
                ui.sensor_view(
                    "drone.scene_cam",
                    name="Sensor Camera",
                ),
                name="Frustums",
            ),
        ),
        ui.object_3d(
            "ellipsoid.world_pos",
            mesh=ui.ellipsoid(
                scale="(0.9, 0.9, 0.38)",
                color=ui.color(
                    0,
                    188,
                    212,
                    28,
                ),
                error_confidence_interval=70.0,
                show_grid=True,
                grid_color=ui.color(
                    255,
                    255,
                    255,
                    120,
                ),
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "drone.world_pos",
            mesh=ui.glb(
                "talon-quad-v2.glb",
                scale=0.65,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="relative",
        ),
        theme=ui.theme(
            mode="dark",
            scheme="default",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
