[package]
name = "aleph-serial-bridge"
license = "MIT OR Apache-2.0"
edition = "2024"
version.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1"

# async
stellarator.path = "../../libs/stellarator"
stellarator.features = ["miette"]
impeller-stellar.path = "../../libs/impeller/stellar"
futures-lite = "2.5.0"

# ser-de
impeller.path = "../../libs/impeller"
impeller.features = ["std"]
impeller-wkt.path = "../../libs/impeller/wkt"
impeller-wkt.features = ["std"]
impeller-frame.path = "../../libs/impeller/frame"
cobs = "0.2"
zerocopy.version = "0.8.2"
db-macros.workspace = true
serde.version = "1.0"
serde.features = ["derive"]
postcard-schema.version = "0.2"
postcard-schema.features = ["derive"]
blackbox.path = "../blackbox"

# rand
fastrand = "2.2.0"
