"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of .drone.rendered.kdl.
"""

# important to keep these active as our only regression tests for the multiple window panels

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.tabs(
            ui.hsplit(
                ui.viewport(
                    name="Viewport",
                    fov=45.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="drone.world_pos + (0,0,0,0, 2,2,2)",
                    look_at="drone.world_pos",
                    smoothing=0.0,
                ),
                ui.vsplit(
                    ui.graph(
                        "drone.angle_desired",
                        name="angle_desired",
                    ),
                    ui.graph(
                        "drone.world_pos.q0, drone.world_pos.q1, drone.world_pos.q2, drone.world_pos.q3, drone.attitude_target",
                        name="World Pos",
                    ),
                    ui.graph(
                        "drone.ang_vel_setpoint",
                    ),
                    share=0.4,
                ),
                name="Viewport",
            ),
            ui.vsplit(
                ui.graph(
                    "drone.gyro",
                ),
                ui.graph(
                    "drone.accel",
                ),
                ui.graph(
                    "drone.magnetometer",
                ),
                name="Sensor Panel",
            ),
        ),
        ui.window(
            path="examples/drone/motor-panel.kdl",
        ),
        ui.window(
            path="examples/drone/rate-control-panel.kdl",
        ),
        ui.vector_arrow(
            "(1, 0, 0)",
            origin="drone.world_pos",
            name="Drone X",
            color="white",
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(0, 1, 0)",
            origin="drone.world_pos",
            name="Drone Y",
            color="white",
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(0, 0, 1)",
            origin="drone.world_pos",
            name="Drone Z",
            color="white",
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.object_3d(
            "drone.world_pos",
            mesh=ui.glb(
                "talon-quad-v2.glb",
                scale=1.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="relative",
            icon=ui.icon(
                builtin="flight",
                color=ui.color(
                    0,
                    188,
                    212,
                    255,
                ),
                size=32.0,
                visibility=ui.visibility_range(
                    min=500.0,
                    max=3.4028235e38,
                    fade_distance=0.0,
                ),
            ),
        ),
        theme=ui.theme(
            mode="dark",
            scheme="default",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
