direction: down

world: World {
  entity_1: Entity 1
  entity_2: Entity 2
}

archetype_a: Archetype A {
  components: Components {
    style.multiple: true
  }
}

archetype_b: Archetype B {
  components: Components {
    style.multiple: true
  }
}

world.entity_1 -- archetype_a.components
world.entity_1 -- archetype_b.components
world.entity_2 -- archetype_b.components
