[package]
name = "adcs"
edition = "2021"
version = "0.1.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roci.workspace = true
roci.features = ["tokio", "std", "csv"]
conduit.workspace = true
conduit.features = ["nox"]
conduit.default-features = false
nox.workspace = true
nox.default-features = false
roci-adcs.workspace = true
basilisk.workspace = true
basilisk.features = ["serde"]
nox-frames.workspace = true
wmm.workspace = true

# config
serde.version = "1.0"
serde.features = ["derive"]
toml = "0.8.14"

# mcu
arrayvec = "0.7.4"
enumflags2 = { version = "0.7.10", features = ["serde"] }
serialport.version = "4.3.0"
serialport.default-features = false

# errors
thiserror = "1.0.61"
anyhow = "1"

# time
hifitime = "3.9"
