[sunline]
q_obs_val = 0.001
q_proc_val = 0.001
covar = [0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004]
sensor_use_threshold = 0.0
ekf_switch = 5.0


[[sunline.css]]
normal_b = [1.0, 0.0, 0.0]
coefficent = 1.0

[[sunline.css]]
normal_b = [-1.0, 0.0, 0.0]
coefficent = 1.0

[[sunline.css]]
normal_b = [0.0, 1.0, 0.0]
coefficent = 1.0

[[sunline.css]]
normal_b = [0.0, -1.0, 0.0]
coefficent = 1.0

[[sunline.css]]
normal_b = [0.0, 0.0, 1.0]
coefficent = 1.0

[[sunline.css]]
normal_b = [0.0, 0.0, -1.0]
coefficent = 1.0

[guidance]
sigma_r0r = [0.0, 0.0, 0.0]

[control]
control_axes_body = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

[control.feedback_config]
p = 4.0
k = 4.0
k_i = 0.0
integral_limit = 500
control_law = 'A'
prior_time = 0
z = [0.0, 0.0, 0.0]
int_sigma = [0.0, 0.0, 0.0]
known_torque_pnt_b_b = [0.0, 0.0, 0.0]
inertia = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

[[control.rw_config.wheels]]
spin_axis = [1.0, 0.0, 0.0]
inertia = 5.781250000000001e-05
max_torque = 0.04

[[control.rw_config.wheels]]
spin_axis = [0.0, 1.0, 0.0]
inertia = 5.781250000000001e-05
max_torque = 0.04

[[control.rw_config.wheels]]
spin_axis = [0.0, 0.0, 1.0]
inertia = 5.781250000000001e-05
max_torque = 0.04

[control.voltage_config]
voltage_max = 10.0
voltage_min = 0.0
k = -1.0


[control.vehicle_config]
spacecraft_inertia_b = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
com_b = [0.0, 0.0, 0.0]
spacecraft_mass = 2.5

[mcu]
path = "/dev/cu.usbmodem70A4923233351"
adcs_format = 39
adcs_update_interval = 10
adcs_cycle_duration = 20
adcs_cycle_interval = 10
gps_update_interval = 1000
gps_cycle_duration = 20
gps_cycle_interval = 10

[mekf]
dt = 0.01
sigma_b = [0.01, 0.01, 0.01]
sigma_g = [0.01, 0.01, 0.01]

[mag_cal]
t = [[ 1.9203215e-03, -6.2749350e-05,  8.8365946e-04],
     [ 8.0907519e-04,  1.8392554e-03, -9.3289115e-04],
     [-4.2906895e-04,  1.2010682e-03,  1.5906866e-03]]
h = [-281.0209, 87.63812, 408.10947]
