
database_url = "postgresql://postgres:secret@postgres.elodin-app-$CLUSTER_NAME.svc.cluster.local:5432/postgres"
redis_url = "redis://redis.elodin-app-$CLUSTER_NAME.svc.cluster.local:6379"
migrate = true

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"

[orca]
vm_namespace = "elodin-vms-$CLUSTER_NAME"
image_name = "us-central1-docker.pkg.dev/elodin-infra/elo-sim-agent/x86_64:$BUILDKITE_COMMIT"

[garbage_collect]
enabled = true
timeout = 600.0

[monte_carlo]
spawn_batches = true
