apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patches:
- target:
    kind: Ingress
    name: elodin
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: $CLUSTER_NAME-docs.elodin.dev
- target:
    namespace: elodin-app
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: elodin-app-$CLUSTER_NAME
- target:
    kind: Namespace
    name: elodin-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-app-$CLUSTER_NAME

images:
- name: elodin-infra/elo-docs
  newName: elodin.azurecr.io/elodin-infra/elo-docs/x86_64
  newTag: $BUILDKITE_COMMIT
