//! KDL-to-Python typed builder code generation (Phase 5 / FR-10).

use crate::color_names::{color_to_ints, name_from_color};
use crate::{KdlSchematicError, parse_schematic};
use impeller2_wkt::*;

/// Convert a KDL schematic into an executable typed `elodin.ui` module.
pub fn schematic_to_python(
    source: &str,
    source_name: Option<&str>,
) -> Result<String, KdlSchematicError> {
    let schematic = parse_schematic(source)?;

    let source_name = source_name.unwrap_or("schematic.kdl");
    let mut out = String::new();
    out.push_str("\"\"\"Generated by `elodin schematic to-python`.\n\n");
    out.push_str("Typed elodin.ui translation of ");
    out.push_str(source_name);
    out.push_str(".\n");
    out.push_str("\"\"\"\n\n");

    for line in source.lines() {
        let comment = line.trim_start();
        if let Some(comment) = comment.strip_prefix("//") {
            out.push('#');
            out.push_str(comment);
            out.push('\n');
        }
    }
    if source
        .lines()
        .any(|line| line.trim_start().starts_with("//"))
    {
        out.push('\n');
    }

    out.push_str("import elodin.ui as ui\n\n");
    out.push_str("def build() -> ui.Schematic:\n");
    out.push_str("    return ");
    out.push_str(&schematic_expr(&schematic).render(1));
    out.push_str("\n\n\n");
    out.push_str("if __name__ == \"__main__\":\n");
    out.push_str("    print(build().emit_kdl())\n");
    Ok(out)
}

#[derive(Debug)]
enum PyExpr {
    Atom(String),
    Call {
        function: &'static str,
        args: Vec<(Option<&'static str>, PyExpr)>,
    },
    List(Vec<PyExpr>),
}

impl PyExpr {
    fn atom(value: impl Into<String>) -> Self {
        Self::Atom(value.into())
    }

    fn call(function: &'static str) -> Self {
        Self::Call {
            function,
            args: Vec::new(),
        }
    }

    fn arg(mut self, value: PyExpr) -> Self {
        let Self::Call { args, .. } = &mut self else {
            unreachable!("arguments can only be added to calls");
        };
        args.push((None, value));
        self
    }

    fn kw(mut self, name: &'static str, value: PyExpr) -> Self {
        let Self::Call { args, .. } = &mut self else {
            unreachable!("arguments can only be added to calls");
        };
        args.push((Some(name), value));
        self
    }

    fn kw_opt(self, name: &'static str, value: Option<PyExpr>) -> Self {
        match value {
            Some(value) => self.kw(name, value),
            None => self,
        }
    }

    fn render(&self, indent: usize) -> String {
        match self {
            Self::Atom(value) => value.clone(),
            Self::List(items) => {
                if items.is_empty() {
                    return "[]".to_string();
                }
                let pad = "    ".repeat(indent);
                let child_pad = "    ".repeat(indent + 1);
                let mut out = String::from("[\n");
                for item in items {
                    out.push_str(&child_pad);
                    out.push_str(&item.render(indent + 1));
                    out.push_str(",\n");
                }
                out.push_str(&pad);
                out.push(']');
                out
            }
            Self::Call { function, args } => {
                if args.is_empty() {
                    return format!("ui.{function}()");
                }
                let pad = "    ".repeat(indent);
                let child_pad = "    ".repeat(indent + 1);
                let mut out = format!("ui.{function}(\n");
                for (name, value) in args {
                    out.push_str(&child_pad);
                    if let Some(name) = name {
                        out.push_str(name);
                        out.push('=');
                    }
                    out.push_str(&value.render(indent + 1));
                    out.push_str(",\n");
                }
                out.push_str(&pad);
                out.push(')');
                out
            }
        }
    }
}

fn schematic_expr(schematic: &Schematic) -> PyExpr {
    let mut call = PyExpr::call("schematic");
    for elem in &schematic.elems {
        call = call.arg(schematic_elem_expr(elem));
    }
    call = call
        .kw_opt(
            "coordinate",
            schematic.frame.map(|frame| {
                let mut coordinate =
                    PyExpr::call("coordinate").kw("frame", py_str(<&str>::from(frame)));
                if let Some(origin) = schematic.origin {
                    coordinate = coordinate
                        .kw("lat", py_f64(origin.latitude))
                        .kw("lon", py_f64(origin.longitude))
                        .kw("alt", py_f64(origin.altitude));
                }
                coordinate.kw_opt("body", schematic.body.map(|body| py_str(body.as_str())))
            }),
        )
        .kw_opt("theme", schematic.theme.as_ref().map(theme_expr))
        .kw_opt("timeline", schematic.timeline.as_ref().map(timeline_expr))
        .kw_opt(
            "skybox",
            schematic.skybox.as_ref().map(|skybox| py_str(&skybox.name)),
        )
        .kw_opt(
            "environment",
            schematic.environment.as_ref().map(environment_expr),
        );
    if schematic.telemetry_mode {
        call = call.kw("telemetry_mode", py_bool(true));
    }
    call
}

fn schematic_elem_expr(elem: &SchematicElem) -> PyExpr {
    match elem {
        SchematicElem::Panel(panel) => panel_expr(panel, None),
        SchematicElem::Object3d(object) => object_expr(object),
        SchematicElem::Line3d(line) => line_expr(line),
        SchematicElem::VectorArrow(arrow) => vector_arrow_expr(arrow),
        SchematicElem::WorldMesh(mesh) => world_mesh_expr(mesh),
        SchematicElem::Window(window) => window_expr(window),
        SchematicElem::Theme(theme) => theme_expr(theme),
        SchematicElem::Timeline(timeline) => timeline_expr(timeline),
        SchematicElem::Coordinate(coordinate) => PyExpr::call("coordinate")
            .kw("frame", py_str(<&str>::from(coordinate.frame)))
            .kw_opt(
                "lat",
                coordinate.origin.map(|origin| py_f64(origin.latitude)),
            )
            .kw_opt(
                "lon",
                coordinate.origin.map(|origin| py_f64(origin.longitude)),
            )
            .kw_opt(
                "alt",
                coordinate.origin.map(|origin| py_f64(origin.altitude)),
            )
            .kw_opt("body", coordinate.body.map(|body| py_str(body.as_str()))),
    }
}

fn panel_expr(panel: &Panel, share: Option<f32>) -> PyExpr {
    match panel {
        Panel::Tabs(panels) => {
            let mut call = PyExpr::call("tabs");
            for panel in panels {
                call = call.arg(panel_expr(panel, None));
            }
            call.kw_opt("share", share.map(py_f32))
        }
        Panel::HSplit(split) => split_expr("hsplit", split, share),
        Panel::VSplit(split) => split_expr("vsplit", split, share),
        Panel::Viewport(viewport) => viewport_expr(viewport, share),
        Panel::Graph(graph) => graph_expr(graph, share),
        Panel::ComponentMonitor(monitor) => PyExpr::call("component_monitor")
            .arg(py_str(&monitor.component_name))
            .kw_opt("name", monitor.name.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
        Panel::GeoPositionGauge(gauge) => PyExpr::call("geo_position_gauge")
            .arg(py_str(&gauge.eql))
            .kw_opt("name", gauge.name.as_deref().map(py_str))
            .kw_opt(
                "source",
                gauge.source.map(|frame| py_str(<&str>::from(frame))),
            )
            .kw("display", py_str(gauge.display.as_str()))
            .kw_opt("share", share.map(py_f32)),
        Panel::OrientationGauge(gauge) => PyExpr::call("orientation_gauge")
            .arg(py_str(&gauge.eql))
            .kw_opt("name", gauge.name.as_deref().map(py_str))
            .kw_opt(
                "source",
                gauge.source.map(|frame| py_str(<&str>::from(frame))),
            )
            .kw_opt(
                "display",
                gauge.display.map(|frame| py_str(<&str>::from(frame))),
            )
            .kw_opt("reference", gauge.reference.map(py_quat))
            .kw_opt("share", share.map(py_f32)),
        Panel::HorizonGauge(gauge) => PyExpr::call("horizon_gauge")
            .arg(py_str(&gauge.eql))
            .kw_opt("name", gauge.name.as_deref().map(py_str))
            .kw_opt(
                "source",
                gauge.source.map(|frame| py_str(<&str>::from(frame))),
            )
            .kw_opt("reference", gauge.reference.map(py_quat))
            .kw_opt("share", share.map(py_f32)),
        Panel::ActionPane(action) => PyExpr::call("action_pane")
            .arg(py_str(&action.name))
            .arg(py_str(&action.lua))
            .kw_opt("share", share.map(py_f32)),
        Panel::QueryTable(table) => PyExpr::call("query_table")
            .arg(py_str(&table.query))
            .kw_opt("name", table.name.as_deref().map(py_str))
            .kw(
                "query_type",
                py_str(match table.query_type {
                    QueryType::EQL => "eql",
                    QueryType::SQL => "sql",
                }),
            )
            .kw_opt("share", share.map(py_f32)),
        Panel::QueryPlot(plot) => PyExpr::call("query_plot")
            .arg(py_str(&plot.name))
            .arg(py_str(&plot.query))
            .kw(
                "refresh_interval_ms",
                py_f64(plot.refresh_interval.as_secs_f64() * 1000.0),
            )
            .kw("auto_refresh", py_bool(plot.auto_refresh))
            .kw("color", py_color(plot.color))
            .kw(
                "query_type",
                py_str(match plot.query_type {
                    QueryType::EQL => "eql",
                    QueryType::SQL => "sql",
                }),
            )
            .kw(
                "plot_mode",
                py_str(match plot.plot_mode {
                    PlotMode::TimeSeries => "time_series",
                    PlotMode::XY => "xy",
                }),
            )
            .kw_opt("x_label", plot.x_label.as_deref().map(py_str))
            .kw_opt("y_label", plot.y_label.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
        Panel::Inspector => PyExpr::call("inspector").kw_opt("share", share.map(py_f32)),
        Panel::Hierarchy => PyExpr::call("hierarchy").kw_opt("share", share.map(py_f32)),
        Panel::SchematicTree(name) => PyExpr::call("schematic_tree")
            .kw_opt("name", name.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
        Panel::DataOverview(name) => PyExpr::call("data_overview")
            .kw_opt("name", name.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
        Panel::VideoStream(stream) => PyExpr::call("video_stream")
            .arg(py_str(&stream.msg_name))
            .kw_opt("name", stream.name.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
        Panel::SensorView(view) => PyExpr::call("sensor_view")
            .arg(py_str(&view.msg_name))
            .kw_opt("name", view.name.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
        Panel::LogStream(stream) => PyExpr::call("log_stream")
            .arg(py_str(&stream.msg_name))
            .kw_opt("name", stream.name.as_deref().map(py_str))
            .kw_opt("share", share.map(py_f32)),
    }
}

fn split_expr(function: &'static str, split: &Split, share: Option<f32>) -> PyExpr {
    let mut call = PyExpr::call(function);
    for (index, panel) in split.panels.iter().enumerate() {
        call = call.arg(panel_expr(panel, split.shares.get(&index).copied()));
    }
    call = call.kw_opt("name", split.name.as_deref().map(py_str));
    if split.active {
        call = call.kw("active", py_bool(true));
    }
    call.kw_opt("share", share.map(py_f32))
}

fn graph_expr(graph: &Graph, share: Option<f32>) -> PyExpr {
    let mut call = PyExpr::call("graph")
        .arg(py_str(&graph.eql))
        .kw_opt("name", graph.name.as_deref().map(py_str));
    if graph.graph_type != GraphType::Line {
        call = call.kw(
            "graph_type",
            py_str(match graph.graph_type {
                GraphType::Line => "line",
                GraphType::Point => "point",
                GraphType::Bar => "bar",
            }),
        );
    }
    if graph.locked {
        call = call.kw("locked", py_bool(true));
    }
    if !graph.auto_y_range {
        call = call
            .kw("auto_y_range", py_bool(false))
            .kw("y_min", py_f64(graph.y_range.start))
            .kw("y_max", py_f64(graph.y_range.end));
    }
    if !graph.colors.is_empty() {
        call = call.kw(
            "colors",
            PyExpr::List(graph.colors.iter().copied().map(py_color).collect()),
        );
    }
    call.kw_opt("share", share.map(py_f32))
}

fn viewport_expr(viewport: &Viewport, share: Option<f32>) -> PyExpr {
    let mut call = PyExpr::call("viewport")
        .kw_opt("name", viewport.name.as_deref().map(py_str))
        .kw("fov", py_f32(viewport.fov))
        .kw_opt("near", viewport.near.map(py_f32))
        .kw_opt("far", viewport.far.map(py_f32))
        .kw_opt("aspect", viewport.aspect.map(py_f32))
        .kw("active", py_bool(viewport.active))
        .kw("show_grid", py_bool(viewport.show_grid))
        .kw("show_arrows", py_bool(viewport.show_arrows))
        .kw("create_frustum", py_bool(viewport.create_frustum))
        .kw("show_frustums", py_bool(viewport.show_frustums))
        .kw("frustums_color", py_color(viewport.frustums_color))
        .kw("projection_color", py_color(viewport.projection_color))
        .kw("frustums_thickness", py_f32(viewport.frustums_thickness))
        .kw("show_view_cube", py_bool(viewport.show_view_cube))
        .kw_opt(
            "view_cube_frame",
            viewport
                .view_cube_frame
                .map(|frame| py_str(<&str>::from(frame))),
        )
        .kw("effects", py_bool(viewport.effects))
        .kw("hdr", py_bool(viewport.hdr))
        .kw("cinematic", py_bool(viewport.cinematic))
        .kw_opt("bloom", viewport.bloom.as_ref().map(bloom_expr))
        .kw_opt("ev100", viewport.ev100.map(py_f32))
        .kw_opt("pos", viewport.pos.as_deref().map(py_str))
        .kw_opt("look_at", viewport.look_at.as_deref().map(py_str))
        .kw_opt("up", viewport.up.as_deref().map(py_str))
        .kw("smoothing", py_f32(viewport.smoothing))
        .kw_opt(
            "frame",
            viewport.frame.map(|frame| py_str(<&str>::from(frame))),
        );
    if !viewport.local_arrows.is_empty() {
        call = call.kw(
            "arrows",
            PyExpr::List(
                viewport
                    .local_arrows
                    .iter()
                    .map(vector_arrow_expr)
                    .collect(),
            ),
        );
    }
    call.kw_opt("share", share.map(py_f32))
}

fn bloom_expr(bloom: &BloomConfig) -> PyExpr {
    PyExpr::call("bloom")
        .kw(
            "preset",
            py_str(match bloom.preset {
                BloomPreset::Natural => "natural",
                BloomPreset::OldSchool => "old_school",
            }),
        )
        .kw_opt("intensity", bloom.intensity.map(py_f32))
        .kw_opt("threshold", bloom.threshold.map(py_f32))
        .kw_opt("threshold_softness", bloom.threshold_softness.map(py_f32))
}

fn theme_expr(theme: &ThemeConfig) -> PyExpr {
    PyExpr::call("theme")
        .kw_opt("mode", theme.mode.as_deref().map(py_str))
        .kw_opt("scheme", theme.scheme.as_deref().map(py_str))
}

fn timeline_expr(timeline: &TimelineConfig) -> PyExpr {
    PyExpr::call("timeline")
        .kw("played_color", py_color(timeline.played_color))
        .kw("future_color", py_color(timeline.future_color))
        .kw("follow_latest", py_bool(timeline.follow_latest))
        .kw_opt("range", timeline.range.as_deref().map(py_str))
}

fn environment_expr(environment: &EnvironmentConfig) -> PyExpr {
    PyExpr::call("environment")
        .kw_opt("sun", environment.sun.as_ref().map(sun_expr))
        .kw("ambient", py_f32(environment.ambient_scale))
        .kw_opt("sky", environment.sky_color.map(py_color))
        .kw_opt(
            "atmosphere",
            environment.atmosphere.as_ref().map(atmosphere_expr),
        )
        .kw_opt("earth", environment.earth.as_ref().map(earth_expr))
}

fn sun_expr(sun: &SunConfig) -> PyExpr {
    PyExpr::call("sun")
        .kw_opt("azimuth", sun.azimuth_deg.map(py_f32))
        .kw_opt("elevation", sun.elevation_deg.map(py_f32))
        .kw("illuminance", py_f32(sun.illuminance))
        .kw("shadows", py_bool(sun.shadows))
        .kw_opt("direction", sun.direction.map(py_vec3_f32))
}

fn atmosphere_expr(atmosphere: &AtmosphereConfig) -> PyExpr {
    PyExpr::call("atmosphere")
        .kw("origin", py_vec3_f64(atmosphere.origin))
        .kw("inner_radius", py_f32(atmosphere.inner_radius))
        .kw("outer_radius", py_f32(atmosphere.outer_radius))
        .kw("ground_albedo", py_vec3_f32(atmosphere.ground_albedo))
        .kw("raymarched", py_bool(atmosphere.raymarched))
}

fn earth_expr(earth: &EarthConfig) -> PyExpr {
    PyExpr::call("earth")
        .kw("stars_density", py_f32(earth.stars.density))
        .kw("stars_size", py_f32(earth.stars.size))
        .kw("stars_brightness", py_f32(earth.stars.brightness))
        .kw("city_lights_density", py_f32(earth.city_lights.density))
        .kw("city_lights_size", py_f32(earth.city_lights.size))
        .kw("city_lights_height", py_f32(earth.city_lights.height))
        .kw(
            "city_lights_brightness",
            py_f32(earth.city_lights.brightness),
        )
        .kw("airglow_density", py_f32(earth.airglow.density))
        .kw("airglow_size", py_f32(earth.airglow.size))
        .kw("airglow_brightness", py_f32(earth.airglow.brightness))
        .kw("night_map_brightness", py_f32(earth.night_map.brightness))
}

fn object_expr(object: &Object3D) -> PyExpr {
    let mut call = PyExpr::call("object_3d")
        .arg(py_str(&object.eql))
        .kw("mesh", object_mesh_expr(&object.mesh))
        .kw_opt(
            "frame",
            object.frame.map(|frame| py_str(<&str>::from(frame))),
        )
        .kw_opt(
            "frame_orientation",
            object
                .frame_orientation
                .map(|frame| py_str(<&str>::from(frame))),
        )
        .kw(
            "orientation",
            py_str(match object.orientation {
                bevy_geo_frames::RotationKind::Relative => "relative",
                bevy_geo_frames::RotationKind::Absolute => "absolute",
            }),
        )
        .kw_opt("icon", object.icon.as_ref().map(icon_expr))
        .kw_opt(
            "visibility",
            object.mesh_visibility_range.as_ref().map(vis_range_expr),
        );
    if let Object3DMesh::Glb { animations, .. } = &object.mesh
        && !animations.is_empty()
    {
        call = call.kw(
            "animate",
            PyExpr::List(
                animations
                    .iter()
                    .map(|animation| {
                        PyExpr::call("joint")
                            .arg(py_str(&animation.joint_name))
                            .arg(py_str(&animation.eql_expr))
                    })
                    .collect(),
            ),
        );
    }
    if !object.thrusters.is_empty() {
        call = call.kw(
            "thrusters",
            PyExpr::List(object.thrusters.iter().map(thruster_expr).collect()),
        );
    }
    call
}

fn object_mesh_expr(mesh: &Object3DMesh) -> PyExpr {
    match mesh {
        Object3DMesh::Glb {
            path,
            scale,
            translate,
            rotate,
            animations: _,
            emissivity,
            glow,
            glow_color,
        } => PyExpr::call("glb")
            .arg(py_str(path))
            .kw("scale", py_f32(*scale))
            .kw("translate", py_vec3_f32(*translate))
            .kw("rotate", py_vec3_f32(*rotate))
            .kw("emissivity", py_f32(*emissivity))
            .kw("glow", py_f32(*glow))
            .kw_opt("glow_color", glow_color.map(py_color)),
        Object3DMesh::Mesh { mesh, material } => match mesh {
            Mesh::Sphere { radius } => PyExpr::call("sphere")
                .kw("radius", py_f32(*radius))
                .kw("color", py_color(material.base_color))
                .kw("emissivity", py_f32(material.emissivity)),
            Mesh::Box { x, y, z } => PyExpr::call("box")
                .kw("x", py_f32(*x))
                .kw("y", py_f32(*y))
                .kw("z", py_f32(*z))
                .kw("color", py_color(material.base_color))
                .kw("emissivity", py_f32(material.emissivity)),
            Mesh::Cylinder { radius, height } => PyExpr::call("cylinder")
                .kw("radius", py_f32(*radius))
                .kw("height", py_f32(*height))
                .kw("color", py_color(material.base_color))
                .kw("emissivity", py_f32(material.emissivity)),
            Mesh::Plane { width, depth } => PyExpr::call("plane")
                .kw("width", py_f32(*width))
                .kw("depth", py_f32(*depth))
                .kw("color", py_color(material.base_color))
                .kw("emissivity", py_f32(material.emissivity)),
        },
        Object3DMesh::Ellipsoid {
            scale,
            color,
            error_covariance_cholesky,
            error_covariance,
            error_confidence_interval,
            show_grid,
            grid_color,
        } => PyExpr::call("ellipsoid")
            .kw("scale", py_str(scale))
            .kw("color", py_color(*color))
            .kw_opt(
                "error_covariance_cholesky",
                error_covariance_cholesky.as_deref().map(py_str),
            )
            .kw_opt("error_covariance", error_covariance.as_deref().map(py_str))
            .kw(
                "error_confidence_interval",
                py_f32(*error_confidence_interval),
            )
            .kw("show_grid", py_bool(*show_grid))
            .kw("grid_color", py_color(*grid_color)),
    }
}

fn icon_expr(icon: &Object3DIcon) -> PyExpr {
    let call = match &icon.source {
        Object3DIconSource::Path(path) => PyExpr::call("icon").kw("path", py_str(path)),
        Object3DIconSource::Builtin(name) => PyExpr::call("icon").kw("builtin", py_str(name)),
    };
    call.kw("color", py_color(icon.color))
        .kw("size", py_f32(icon.size))
        .kw_opt(
            "visibility",
            icon.visibility_range.as_ref().map(vis_range_expr),
        )
}

fn vis_range_expr(range: &VisRange) -> PyExpr {
    PyExpr::call("visibility_range")
        .kw("min", py_f32(range.min))
        .kw("max", py_f32(range.max))
        .kw("fade_distance", py_f32(range.fade_distance))
}

fn thruster_expr(thruster: &Thruster) -> PyExpr {
    let mut call = PyExpr::call("thruster")
        .kw_opt("name", thruster.name.as_deref().map(py_str))
        .kw("body_frame", py_bool(thruster.body_frame))
        .kw("position", py_vec3_f32(thruster.position))
        .kw_opt("direction", thruster.direction.map(py_vec3_f32))
        .kw("intensity", py_str(&thruster.intensity))
        .kw("effect", py_str(&thruster.effect))
        .kw_opt("emission_rate", thruster.emission_rate.map(py_f32))
        .kw("cutoff", py_f32(thruster.cutoff))
        .kw("scale", py_f32(thruster.scale))
        .kw_opt("light", thruster.light.as_ref().map(thruster_light_expr));
    if !thruster.extra_effects.is_empty() {
        call = call.kw(
            "extra_effects",
            PyExpr::List(
                thruster
                    .extra_effects
                    .iter()
                    .map(|effect| py_str(effect))
                    .collect(),
            ),
        );
    }
    call
}

fn thruster_light_expr(light: &ThrusterLight) -> PyExpr {
    PyExpr::call("thruster_light")
        .kw("color", py_vec3_f32(light.color))
        .kw("intensity", py_f32(light.intensity))
        .kw("range", py_f32(light.range))
        .kw("offset", py_f32(light.offset))
        .kw_opt("spot_angle", light.spot_angle.map(py_f32))
        .kw("shadows", py_bool(light.shadows))
}

fn line_expr(line: &Line3d) -> PyExpr {
    PyExpr::call("line_3d")
        .arg(py_str(&line.eql))
        .kw("line_width", py_f32(line.line_width))
        .kw_opt("color", line.color.map(py_color))
        .kw_opt("future_color", line.future_color.map(py_color))
        .kw("perspective", py_bool(line.perspective))
        .kw_opt("frame", line.frame.map(|frame| py_str(<&str>::from(frame))))
}

fn vector_arrow_expr(arrow: &VectorArrow3d) -> PyExpr {
    PyExpr::call("vector_arrow")
        .arg(py_str(&arrow.vector))
        .kw_opt("origin", arrow.origin.as_deref().map(py_str))
        .kw_opt("name", arrow.name.as_deref().map(py_str))
        .kw("color", py_color(arrow.color))
        .kw("scale", py_f64(arrow.scale))
        .kw("body_frame", py_bool(arrow.body_frame))
        .kw("normalize", py_bool(arrow.normalize))
        .kw("show_name", py_bool(arrow.show_name))
        .kw("thickness", py_f32(arrow.thickness.value()))
        .kw(
            "label_position",
            match arrow.label_position {
                LabelPosition::None => PyExpr::atom("None"),
                LabelPosition::Proportionate(value) => py_str(&format!("{value:?}")),
                LabelPosition::Absolute(value) => py_str(&format!("{value:?}m")),
            },
        )
        .kw_opt(
            "frame",
            arrow.frame.map(|frame| py_str(<&str>::from(frame))),
        )
}

fn world_mesh_expr(mesh: &WorldMesh) -> PyExpr {
    PyExpr::call("world_mesh")
        .arg(py_str(&mesh.region))
        .kw_opt(
            "lod_count",
            mesh.lod_count.map(|value| PyExpr::atom(value.to_string())),
        )
        .kw_opt("translate", mesh.translate.map(py_vec3_f64))
        .kw_opt("frame", mesh.frame.map(|frame| py_str(<&str>::from(frame))))
        .kw("visible", py_bool(mesh.visible))
}

fn window_expr(window: &WindowSchematic) -> PyExpr {
    PyExpr::call("window")
        .kw_opt("path", window.path.as_deref().map(py_str))
        .kw_opt("title", window.title.as_deref().map(py_str))
        .kw_opt(
            "screen",
            window.screen.map(|value| PyExpr::atom(value.to_string())),
        )
        .kw_opt(
            "rect",
            window.screen_rect.map(|rect| {
                PyExpr::atom(format!(
                    "({}, {}, {}, {})",
                    rect.x, rect.y, rect.width, rect.height
                ))
            }),
        )
}

fn py_str(value: &str) -> PyExpr {
    PyExpr::atom(python_string_literal(value))
}

fn py_bool(value: bool) -> PyExpr {
    PyExpr::atom(if value { "True" } else { "False" })
}

fn py_f32(value: f32) -> PyExpr {
    PyExpr::atom(format!("{value:?}"))
}

fn py_f64(value: f64) -> PyExpr {
    PyExpr::atom(format!("{value:?}"))
}

fn py_color(color: Color) -> PyExpr {
    if let Some(name) = name_from_color(&color) {
        return py_str(name);
    }
    let (r, g, b, a) = color_to_ints(&color);
    PyExpr::call("color")
        .arg(PyExpr::atom(r.to_string()))
        .arg(PyExpr::atom(g.to_string()))
        .arg(PyExpr::atom(b.to_string()))
        .arg(PyExpr::atom(a.to_string()))
}

fn py_vec3_f32((x, y, z): (f32, f32, f32)) -> PyExpr {
    PyExpr::atom(format!("({x:?}, {y:?}, {z:?})"))
}

fn py_vec3_f64((x, y, z): (f64, f64, f64)) -> PyExpr {
    PyExpr::atom(format!("({x:?}, {y:?}, {z:?})"))
}

fn py_quat([x, y, z, w]: [f64; 4]) -> PyExpr {
    PyExpr::atom(format!("({x:?}, {y:?}, {z:?}, {w:?})"))
}

fn python_string_literal(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                use std::fmt::Write;
                write!(out, "\\u{:04x}", c as u32).expect("writing to String cannot fail");
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_typed_module_and_preserves_comments() {
        let source = "// dashboard title\nviewport name=\"A\"\n";
        let python = schematic_to_python(source, Some("main.kdl")).unwrap();
        assert!(python.contains("# dashboard title"));
        assert!(python.contains("def build() -> ui.Schematic:"));
        assert!(python.contains("ui.viewport("));
        assert!(!python.contains("SOURCE_KDL"));
        assert!(!python.contains("ui.from_kdl"));
    }

    #[test]
    fn rejects_invalid_kdl() {
        assert!(schematic_to_python("viewport {", None).is_err());
    }

    #[test]
    fn escapes_python_string_content() {
        assert_eq!(
            python_string_literal("a \"quote\" \\\\ path\n"),
            "\"a \\\"quote\\\" \\\\\\\\ path\\n\""
        );
    }
}
