//! Lossless KDL-to-Python migration scaffold (Phase 5 / FR-10).

use crate::{KdlSchematicError, parse_schematic};

/// Convert a KDL schematic into an executable `elodin.ui` Python module.
///
/// The first migration step deliberately preserves the source KDL byte for
/// byte inside `SOURCE_KDL`. This supports every parser feature immediately;
/// generated modules can then be incrementally rewritten to typed builders.
pub fn schematic_to_python(
    source: &str,
    source_name: Option<&str>,
) -> Result<String, KdlSchematicError> {
    parse_schematic(source)?;

    let source_name = source_name.unwrap_or("schematic.kdl");
    let mut out = String::new();
    out.push_str("\"\"\"Generated by `elodin schematic to-python`.\n\n");
    out.push_str("Lossless migration scaffold for ");
    out.push_str(source_name);
    out.push_str(". Replace SOURCE_KDL incrementally with typed elodin.ui builders.\n");
    out.push_str("\"\"\"\n\n");

    for line in source.lines() {
        let comment = line.trim_start();
        if let Some(comment) = comment.strip_prefix("//") {
            out.push('#');
            out.push_str(comment);
            out.push('\n');
        }
    }
    if source
        .lines()
        .any(|line| line.trim_start().starts_with("//"))
    {
        out.push('\n');
    }

    out.push_str("import elodin.ui as ui\n\n");
    out.push_str("SOURCE_KDL = (\n");
    for line in source.split_inclusive('\n') {
        out.push_str("    ");
        out.push_str(&python_string_literal(line));
        out.push('\n');
    }
    if source.is_empty() {
        out.push_str("    \"\"\n");
    }
    out.push_str(")\n\n\n");
    out.push_str("def build() -> ui.Schematic:\n");
    out.push_str("    return ui.from_kdl(SOURCE_KDL)\n\n\n");
    out.push_str("if __name__ == \"__main__\":\n");
    out.push_str("    print(build().emit_kdl())\n");
    Ok(out)
}

fn python_string_literal(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                use std::fmt::Write;
                write!(out, "\\u{:04x}", c as u32).expect("writing to String cannot fail");
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_executable_module_shape_and_preserves_comments() {
        let source = "// dashboard title\nviewport name=\"A\"\n";
        let python = schematic_to_python(source, Some("main.kdl")).unwrap();
        assert!(python.contains("# dashboard title"));
        assert!(python.contains("\"// dashboard title\\n\""));
        assert!(python.contains("def build() -> ui.Schematic:"));
        assert!(python.contains("return ui.from_kdl(SOURCE_KDL)"));
    }

    #[test]
    fn rejects_invalid_kdl() {
        assert!(schematic_to_python("viewport {", None).is_err());
    }

    #[test]
    fn escapes_python_string_content() {
        assert_eq!(
            python_string_literal("a \"quote\" \\\\ path\n"),
            "\"a \\\"quote\\\" \\\\\\\\ path\\n\""
        );
    }
}
