"""Python schematic for the geo-frames example.

Matches the KDL stored at ``schematics/main.kdl`` when the example runs,
including ``db:`` asset paths.
"""

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.hsplit(
            ui.vsplit(
                ui.viewport(
                    name="ECEF Equator",
                    fov=45.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=True,
                    cinematic=False,
                    pos="(0,0,0,1, 8000000,-80000000, 0)",
                    look_at="(0,0,0,1, 0,0,0)",
                    up="(0,0,1)",
                    smoothing=0.0,
                    frame="ECEF",
                ),
                ui.viewport(
                    name="ECEF Oblique",
                    fov=45.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=True,
                    cinematic=False,
                    pos="(0,0,0,1, 46000000,-46000000, 46000000)",
                    look_at="(0,0,0,1, 0,0,0)",
                    up="(0,0,1)",
                    smoothing=0.0,
                    frame="ECEF",
                ),
            ),
            ui.tabs(
                ui.viewport(
                    name="Frames",
                    fov=45.0,
                    active=True,
                    show_grid=False,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=True,
                    cinematic=False,
                    pos="(0,0,0,1, 4000000,4000000,-3000000)",
                    look_at="(0,0,0,1, 0,0,0)",
                    smoothing=0.0,
                    frame="NED",
                ),
                ui.inspector(),
                ui.hierarchy(),
            ),
        ),
        ui.object_3d(
            "earth.world_pos",
            mesh=ui.glb(
                "db:earth.glb",
                scale=1.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="ECEF",
            orientation="absolute",
            icon=ui.icon(
                builtin="public",
                color="white",
                size=64.0,
            ),
        ),
        ui.object_3d(
            "ecef_equator_x_pos.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="location_on",
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                size=48.0,
            ),
        ),
        # TODO: These compasses are rotated such that they're correct with
        # respect to the ENU origin, not with respect to where they are on the
        # world proper.
        # 
        # ui.object_3d(
        #     "(0,0,0,1, ecef_equator_x_pos.world_pos[4],ecef_equator_x_pos.world_pos[5],ecef_equator_x_pos.world_pos[6])",
        #     mesh=ui.glb(
        #         "db:compass.glb",
        #         scale=1000000.0,
        #         translate=(0.0, 0.0, 0.0),
        #         rotate=(0.0, 0.0, 0.0),
        #         emissivity=0.0,
        #         glow=0.0,
        #     ),
        #     frame="ECEF",
        #     frame_orientation="ENU",
        #     orientation="absolute",
        # ),
        ui.object_3d(
            "ecef_equator_y_pos.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="location_on",
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                size=48.0,
            ),
        ),
        # ui.object_3d(
        #     "(0,0,0,1, ecef_equator_y_pos.world_pos[4],ecef_equator_y_pos.world_pos[5],ecef_equator_y_pos.world_pos[6])",
        #     mesh=ui.glb(
        #         "db:compass.glb",
        #         scale=1000000.0,
        #         translate=(0.0, 0.0, 0.0),
        #         rotate=(0.0, 0.0, 0.0),
        #         emissivity=0.0,
        #         glow=0.0,
        #     ),
        #     frame="ECEF",
        #     frame_orientation="ENU",
        #     orientation="absolute",
        # ),
        ui.object_3d(
            "ecef_equator_x_neg.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="location_on",
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                size=48.0,
            ),
        ),
        # ui.object_3d(
        #     "(0,0,0,1, ecef_equator_x_neg.world_pos[4],ecef_equator_x_neg.world_pos[5],ecef_equator_x_neg.world_pos[6])",
        #     mesh=ui.glb(
        #         "db:compass.glb",
        #         scale=1000000.0,
        #         translate=(0.0, 0.0, 0.0),
        #         rotate=(0.0, 0.0, 0.0),
        #         emissivity=0.0,
        #         glow=0.0,
        #     ),
        #     frame="ECEF",
        #     frame_orientation="ENU",
        #     orientation="absolute",
        # ),
        ui.object_3d(
            "ecef_equator_y_neg.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="location_on",
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                size=48.0,
            ),
        ),
        # ui.object_3d(
        #     "(0,0,0,1, ecef_equator_y_neg.world_pos[4],ecef_equator_y_neg.world_pos[5],ecef_equator_y_neg.world_pos[6])",
        #     mesh=ui.glb(
        #         "db:compass.glb",
        #         scale=1000000.0,
        #         translate=(0.0, 0.0, 0.0),
        #         rotate=(0.0, 0.0, 0.0),
        #         emissivity=0.0,
        #         glow=0.0,
        #     ),
        #     frame="ECEF",
        #     frame_orientation="ENU",
        #     orientation="absolute",
        # ),
        ui.object_3d(
            "ecef_north_pole.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="location_on",
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                size=48.0,
            ),
        ),
        # ui.object_3d(
        #     "(0,0,0,1, ecef_north_pole.world_pos[4],ecef_north_pole.world_pos[5],ecef_north_pole.world_pos[6])",
        #     mesh=ui.glb(
        #         "db:compass.glb",
        #         scale=1000000.0,
        #         translate=(0.0, 0.0, 0.0),
        #         rotate=(0.0, 0.0, 0.0),
        #         emissivity=0.0,
        #         glow=0.0,
        #     ),
        #     frame="ECEF",
        #     frame_orientation="ENU",
        #     orientation="absolute",
        # ),
        ui.object_3d(
            "ecef_south_pole.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="location_on",
                color=ui.color(
                    156,
                    39,
                    176,
                    255,
                ),
                size=48.0,
            ),
        ),
        # ui.object_3d(
        #     "(0,0,0,1, ecef_south_pole.world_pos[4],ecef_south_pole.world_pos[5],ecef_south_pole.world_pos[6])",
        #     mesh=ui.glb(
        #         "db:compass.glb",
        #         scale=1000000.0,
        #         translate=(0.0, 0.0, 0.0),
        #         rotate=(0.0, 0.0, 0.0),
        #         emissivity=0.0,
        #         glow=0.0,
        #     ),
        #     frame="ECEF",
        #     frame_orientation="ENU",
        #     orientation="absolute",
        # ),
        ui.object_3d(
            "ned_origin.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    244,
                    67,
                    54,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="NED",
            orientation="relative",
            icon=ui.icon(
                builtin="my_location",
                color=ui.color(
                    244,
                    67,
                    54,
                    255,
                ),
                size=56.0,
            ),
        ),
        ui.object_3d(
            "(0,0,0,1, ned_origin.world_pos[4],ned_origin.world_pos[5],ned_origin.world_pos[6])",
            mesh=ui.glb(
                "db:compass.glb",
                scale=1000000.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="NED",
            frame_orientation="ENU",
            orientation="absolute",
        ),
        ui.object_3d(
            "enu_far_east.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    33,
                    150,
                    243,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ENU",
            orientation="relative",
            icon=ui.icon(
                builtin="explore",
                color=ui.color(
                    33,
                    150,
                    243,
                    255,
                ),
                size=56.0,
            ),
        ),
        ui.object_3d(
            "(0,0,0,1, enu_far_east.world_pos[4],enu_far_east.world_pos[5],enu_far_east.world_pos[6])",
            mesh=ui.glb(
                "db:compass.glb",
                scale=1000000.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="ENU",
            orientation="absolute",
        ),
        ui.object_3d(
            "ecef_far_up.world_pos",
            mesh=ui.box(
                x=500000.0,
                y=500000.0,
                z=500000.0,
                color=ui.color(
                    76,
                    175,
                    80,
                    255,
                ),
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="gps_fixed",
                color=ui.color(
                    76,
                    175,
                    80,
                    255,
                ),
                size=56.0,
            ),
        ),
        ui.object_3d(
            "(0,0,0,1, ecef_far_up.world_pos[4],ecef_far_up.world_pos[5],ecef_far_up.world_pos[6])",
            mesh=ui.glb(
                "db:compass.glb",
                scale=1000000.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="ECEF",
            frame_orientation="ENU",
            orientation="absolute",
        ),
        ui.object_3d(
            "ecef_orbit_line.world_pos",
            mesh=ui.sphere(
                radius=125000.0,
                color="cyan",
                emissivity=0.0,
            ),
            frame="ECEF",
            orientation="relative",
            icon=ui.icon(
                builtin="satellite_alt",
                color="cyan",
                size=48.0,
            ),
        ),
        ui.line_3d(
            "ned_origin.world_pos",
            line_width=2.0,
            color=ui.color(
                244,
                67,
                54,
                255,
            ),
            perspective=True,
            frame="NED",
        ),
        ui.line_3d(
            "enu_far_east.world_pos",
            line_width=2.0,
            color=ui.color(
                33,
                150,
                243,
                255,
            ),
            perspective=True,
            frame="ENU",
        ),
        ui.line_3d(
            "ecef_far_up.world_pos",
            line_width=2.0,
            color=ui.color(
                76,
                175,
                80,
                255,
            ),
            perspective=True,
            frame="ECEF",
        ),
        ui.line_3d(
            "ecef_orbit_line.world_pos",
            line_width=4.0,
            color="cyan",
            perspective=False,
            frame="ECEF",
        ),
        ui.vector_arrow(
            "(0, 1, 0)",
            origin="ned_origin.world_pos",
            name="NED Y-axis",
            color=ui.color(
                244,
                67,
                54,
                255,
            ),
            scale=1000000.0,
            body_frame=True,
            normalize=True,
            show_name=True,
            thickness=2500.0,
            label_position="0.0",
            frame="NED",
        ),
        ui.vector_arrow(
            "(0, 1, 0)",
            origin="enu_far_east.world_pos",
            name="ENU Y-axis",
            color=ui.color(
                33,
                150,
                243,
                255,
            ),
            scale=1000000.0,
            body_frame=True,
            normalize=True,
            show_name=True,
            thickness=2500.0,
            label_position="0.0",
            frame="ENU",
        ),
        ui.vector_arrow(
            "(0, 1, 0)",
            origin="ecef_far_up.world_pos",
            name="ECEF Y-axis",
            color=ui.color(
                76,
                175,
                80,
                255,
            ),
            scale=1000000.0,
            body_frame=True,
            normalize=True,
            show_name=True,
            thickness=2500.0,
            label_position="0.0",
            frame="ECEF",
        ),
        coordinate=ui.coordinate(
            frame="NED",
            lat=34.72,
            lon=-86.64,
            alt=180.5,
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
