"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of crazyflie-edu.kdl.
"""

# Motor position indicators
# Rotor disc visualization
# Thrust visualization arrows

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.tabs(
            ui.hsplit(
                ui.viewport(
                    name="3D View",
                    fov=45.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="crazyflie.world_pos + (0,0,0,0, 0.2, 0.2, 0.2)",
                    look_at="crazyflie.world_pos",
                    smoothing=0.0,
                ),
                ui.vsplit(
                    ui.graph(
                        "crazyflie.gyro",
                        name="Gyroscope (rad/s)",
                    ),
                    ui.graph(
                        "crazyflie.accel",
                        name="Accelerometer (g)",
                    ),
                    ui.graph(
                        "crazyflie.motor_pwm",
                        name="Motor PWM",
                    ),
                    share=0.35,
                ),
                name="Simulation",
            ),
            ui.vsplit(
                ui.graph(
                    "crazyflie.motor_rpm",
                    name="Motor RPM",
                ),
                ui.graph(
                    "crazyflie.thrust",
                    name="Motor Thrust (N)",
                ),
                ui.graph(
                    "crazyflie.motor_command",
                    name="Motor Command (from SITL)",
                ),
                name="Motors",
            ),
            ui.vsplit(
                ui.graph(
                    "crazyflie.is_armed_control",
                    name="Armed State (Q to toggle)",
                ),
                ui.graph(
                    "crazyflie.button_blue",
                    name="Blue Button (Shift)",
                ),
                ui.graph(
                    "crazyflie.button_yellow",
                    name="Yellow Button (E)",
                ),
                ui.graph(
                    "crazyflie.button_green",
                    name="Green Button (R)",
                ),
                ui.graph(
                    "crazyflie.button_red",
                    name="Red Button (T)",
                ),
                name="Controls",
            ),
        ),
        ui.object_3d(
            "crazyflie.world_pos",
            mesh=ui.glb(
                "crazyflie.glb",
                scale=0.7,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="relative",
            animate=[
                ui.joint(
                    "Root.Propeller_0",
                    "(0, crazyflie.propeller_angle[0], 0)",
                ),
                ui.joint(
                    "Root.Propeller_1",
                    "(0, crazyflie.propeller_angle[1], 0)",
                ),
                ui.joint(
                    "Root.Propeller_2",
                    "(0, crazyflie.propeller_angle[2], 0)",
                ),
                ui.joint(
                    "Root.Propeller_3",
                    "(0, crazyflie.propeller_angle[3], 0)",
                ),
            ],
        ),
        ui.vector_arrow(
            "(0.707, -0.707, 0)",
            origin="crazyflie.world_pos",
            name="M1: FR",
            color=ui.color(
                255,
                255,
                0,
                10,
            ),
            scale=0.046,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(0.707, 0.707, 0)",
            origin="crazyflie.world_pos",
            name="M2: FL",
            color=ui.color(
                255,
                255,
                0,
                10,
            ),
            scale=0.046,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(-0.707, 0.707, 0)",
            origin="crazyflie.world_pos",
            name="M3: BL",
            color=ui.color(
                255,
                255,
                0,
                10,
            ),
            scale=0.046,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(-0.707, -0.707, 0)",
            origin="crazyflie.world_pos",
            name="M4: BR",
            color=ui.color(
                255,
                255,
                0,
                10,
            ),
            scale=0.046,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.object_3d(
            "crazyflie.world_pos + (0,0,0,0, 0.0325, -0.0325, 0.013)",
            mesh=ui.cylinder(
                radius=0.0225,
                height=0.002,
                color=ui.color(
                    0,
                    255,
                    255,
                    30,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "crazyflie.world_pos + (0,0,0,0, 0.0325, 0.0325, 0.013)",
            mesh=ui.cylinder(
                radius=0.0225,
                height=0.002,
                color=ui.color(
                    255,
                    0,
                    0,
                    30,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "crazyflie.world_pos + (0,0,0,0, -0.0325, 0.0325, 0.013)",
            mesh=ui.cylinder(
                radius=0.0225,
                height=0.002,
                color=ui.color(
                    0,
                    255,
                    255,
                    30,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "crazyflie.world_pos + (0,0,0,0, -0.0325, -0.0325, 0.013)",
            mesh=ui.cylinder(
                radius=0.0225,
                height=0.002,
                color=ui.color(
                    255,
                    0,
                    0,
                    30,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.vector_arrow(
            "crazyflie.thrust_viz_m1",
            origin="crazyflie.world_pos + (0,0,0,0, 0.0325, -0.0325, 0.013)",
            color=ui.color(
                0,
                255,
                255,
                20,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "crazyflie.thrust_viz_m2",
            origin="crazyflie.world_pos + (0,0,0,0, 0.0325, 0.0325, 0.013)",
            color=ui.color(
                255,
                0,
                0,
                20,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "crazyflie.thrust_viz_m3",
            origin="crazyflie.world_pos + (0,0,0,0, -0.0325, 0.0325, 0.013)",
            color=ui.color(
                0,
                255,
                255,
                20,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "crazyflie.thrust_viz_m4",
            origin="crazyflie.world_pos + (0,0,0,0, -0.0325, -0.0325, 0.013)",
            color=ui.color(
                255,
                0,
                0,
                20,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        theme=ui.theme(
            mode="dark",
            scheme="default",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
