"""Public API surface of ``elodin.db`` (includes the native classes that the
runtime module re-exports, which type checkers cannot see into)."""

from typing import Any, Dict, Iterable, Iterator, List, Optional, Tuple, Union

import numpy as np

class Field:
    prim: str
    shape: Tuple[int, ...]
    element_names: Tuple[str, ...]
    def __getitem__(self, dims: Union[int, Tuple[int, ...]]) -> "Field": ...
    def labeled(self, *names: str) -> "Field": ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def count(self) -> int: ...
    @property
    def nbytes(self) -> int: ...

f64: Field
f32: Field
i64: Field
i32: Field
i16: Field
i8: Field
u64: Field
u32: Field
u16: Field
u8: Field
bool_: Field

class ComponentInfo:
    name: str
    prim_type: str
    shape: List[int]
    element_names: List[str]
    metadata: Dict[str, str]

class Sample:
    name: str
    timestamp_us: int
    values: np.ndarray

class StreamRow:
    timestamp_us: int
    values: Dict[str, np.ndarray]
    timestamps: Dict[str, int]
    def __getitem__(self, name: str) -> np.ndarray: ...
    def __contains__(self, name: str) -> bool: ...

class ComponentStream(Iterator[StreamRow]):
    def __iter__(self) -> "ComponentStream": ...
    def __next__(self) -> StreamRow: ...
    def close(self) -> None: ...
    def __enter__(self) -> "ComponentStream": ...
    def __exit__(self, *exc: object) -> bool: ...

class MessageStream(Iterator[Tuple[int, Any]]):
    def __iter__(self) -> "MessageStream": ...
    def __next__(self) -> Tuple[int, Any]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "MessageStream": ...
    def __exit__(self, *exc: object) -> bool: ...

class TableWriter:
    def __init__(
        self,
        addr: str,
        schema: Dict[str, Field],
        queue: str = "drop-oldest",
        maxlen: int = 1024,
        timestamp: str = "us",
    ) -> None: ...
    @property
    def dropped(self) -> int: ...
    @property
    def last_error(self) -> Optional[str]: ...
    def state(self) -> str: ...
    @property
    def row_size(self) -> int: ...
    def write(
        self,
        timestamp_us: Optional[int] = None,
        values: Optional[Dict[str, Any]] = None,
        *,
        timestamp_ns: Optional[int] = None,
    ) -> None: ...
    def write_nowait(
        self,
        timestamp_us: Optional[int] = None,
        values: Optional[Dict[str, Any]] = None,
        *,
        timestamp_ns: Optional[int] = None,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "TableWriter": ...
    def __exit__(self, *exc: object) -> bool: ...

def sql_table_name(component_name: str) -> str: ...

class Client:
    def __init__(self, addr: str) -> None: ...
    @classmethod
    def connect(cls, addr: str) -> "Client": ...
    @property
    def addr(self) -> str: ...
    def table_writer(
        self,
        schema: Dict[str, Field],
        queue: str = "drop-oldest",
        maxlen: int = 1024,
        timestamp: str = "us",
    ) -> TableWriter: ...
    def send(self, name: str, values: Any, timestamp_us: int) -> None: ...
    def send_msg(self, name: str, payload: Any, timestamp_us: int) -> None: ...
    def get_msgs(
        self,
        name: str,
        start_us: int,
        stop_us: int,
        limit: Optional[int] = None,
        raw: bool = False,
    ) -> List[Tuple[int, Any]]: ...
    def msg_stream(self, name: str, maxlen: int = 1024, raw: bool = False) -> MessageStream: ...
    def components(self) -> Dict[str, ComponentInfo]: ...
    def earliest_timestamp(self) -> int: ...
    def stream(
        self,
        names: Union[str, Iterable[str]],
        rate_hz: Optional[float] = None,
        start: Union[str, int, None] = None,
        maxlen: int = 1024,
    ) -> ComponentStream: ...
    def latest(self, name: str) -> Optional[Sample]: ...
    def time_series(
        self,
        name: str,
        start_us: int,
        stop_us: int,
        limit: Optional[int] = None,
    ) -> Tuple[np.ndarray, np.ndarray]: ...
    def sql(self, query: str) -> Any: ...  # pyarrow.Table
    def state(self) -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Client": ...
    def __exit__(self, *exc: object) -> bool: ...

class Server:
    @staticmethod
    def start(path: str, addr: str = "127.0.0.1:2240") -> "Server": ...
    @property
    def addr(self) -> str: ...
    @property
    def path(self) -> str: ...
    def stop(self) -> None: ...
    def __enter__(self) -> "Server": ...
    def __exit__(self, *exc: object) -> bool: ...

__all__: List[str]
