[package]
name = "helmholtz-chamber"
edition = "2021"
publish = false
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.3.0"
roci.workspace = true
roci.features = ["tokio", "std"]
