apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elodin
spec:
  ingressClassName: traefik
  defaultBackend:
    service:
      name: elo-dashboard
      port:
        number: 80
  rules:
  - host: app.elodin.dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: elo-dashboard
            port: 
              number: 80
      - path: /elodin.types.api.Api
        pathType: Prefix
        backend:
          service:
            name: elo-atc
            port:
              number: 50051
      - path: /sim/ws
        pathType: Prefix
        backend:
          service:
            name: elo-atc
            port:
              number: 50051
      - path: /stripe/webhook
        pathType: Prefix
        backend:
          service:
            name: elo-atc
            port:
              number: 50051
