"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of monte-carlo.kdl.
"""

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.viewport(
            name="Monte Carlo",
            fov=45.0,
            active=True,
            show_grid=True,
            show_arrows=True,
            create_frustum=False,
            show_frustums=False,
            frustums_color="yellow",
            projection_color="white",
            frustums_thickness=0.006,
            show_view_cube=True,
            effects=True,
            hdr=True,
            cinematic=False,
            bloom=ui.bloom(
                preset="old_school",
                intensity=0.35,
                threshold=0.55,
                threshold_softness=0.2,
            ),
            pos="(0,0,0,1, vehicle.position[0] - 8, -10, 5)",
            look_at="(0,0,0,1, vehicle.position[0], 0, 0)",
            smoothing=0.0,
        ),
        ui.object_3d(
            "(0,0,0,1, vehicle.position[0], 0, 0)",
            mesh=ui.sphere(
                radius=0.25,
                color=ui.color(
                    80,
                    170,
                    255,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
            thrusters=[
                ui.thruster(
                    name="Forward specific force",
                    body_frame=True,
                    position=(-0.35, 0.0, 0.0),
                    direction=(-1.0, 0.0, 0.0),
                    intensity="vehicle.specific_force[0] / 20.0",
                    effect="plume",
                    emission_rate=420.0,
                    cutoff=0.02,
                    scale=1.0,
                ),
                ui.thruster(
                    name="Reverse specific force",
                    body_frame=True,
                    position=(0.35, 0.0, 0.0),
                    direction=(1.0, 0.0, 0.0),
                    intensity="vehicle.specific_force[0] / -20.0",
                    effect="plume",
                    emission_rate=420.0,
                    cutoff=0.02,
                    scale=1.0,
                ),
            ],
        ),
        ui.graph(
            "vehicle.specific_force",
            name="Specific force",
        ),
        ui.graph(
            "vehicle.position",
            name="Position",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
