// elodin_lapack VM module: provides LAPACK functions to IREE via OpenBLAS.
//
// Each exported function receives hal.buffer_view inputs, maps them to host
// memory, calls the corresponding LAPACK routine, and returns
// hal.buffer_view outputs.
//
// Signatures must exactly match the VM imports generated by the
// LapackCustomCallRewriter compiler patch.

#include "lapack_module.h"

#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <dlfcn.h>

#include "iree/hal/api.h"
#include "iree/modules/hal/types.h"
#include "iree/vm/native_module.h"
#include "iree/vm/shims.h"

// LAPACKE C interface function pointer types.
// Nix's OpenBLAS is built with USE64BITINT, so lapack_int is int64_t.
// All integer parameters (dimensions, leading dimensions, pivot arrays,
// info return) must use int64_t to match.
#include <stdint.h>
typedef int64_t lapack_int;

typedef lapack_int (*LAPACKE_dgesdd_fn)(int, char, lapack_int, lapack_int, double*, lapack_int,
                                 double*, double*, lapack_int, double*, lapack_int);
typedef lapack_int (*LAPACKE_dpotrf_fn)(int, char, lapack_int, double*, lapack_int);
typedef lapack_int (*LAPACKE_dgetrf_fn)(int, lapack_int, lapack_int, double*, lapack_int, lapack_int*);
typedef lapack_int (*LAPACKE_dgetrs_fn)(int, char, lapack_int, lapack_int, double*, lapack_int,
                                  lapack_int*, double*, lapack_int);
typedef void (*cblas_dtrsm_fn)(int, int, int, int, int, int64_t, int64_t,
                                double, double*, int64_t, double*, int64_t);
typedef lapack_int (*LAPACKE_dgeqrf_fn)(int, lapack_int, lapack_int, double*, lapack_int, double*);
typedef lapack_int (*LAPACKE_dorgqr_fn)(int, lapack_int, lapack_int, lapack_int, double*, lapack_int, double*);
typedef lapack_int (*LAPACKE_dsyevd_fn)(int, char, char, lapack_int, double*, lapack_int, double*);

static LAPACKE_dgesdd_fn fn_dgesdd;
static LAPACKE_dpotrf_fn fn_dpotrf;
static LAPACKE_dgetrf_fn fn_dgetrf;
static LAPACKE_dgetrs_fn fn_dgetrs;
static cblas_dtrsm_fn    fn_dtrsm;
static LAPACKE_dgeqrf_fn fn_dgeqrf;
static LAPACKE_dorgqr_fn fn_dorgqr;
static LAPACKE_dsyevd_fn fn_dsyevd;

typedef void (*openblas_set_num_threads_fn)(int);

static void elodin_lapack_load_from(void* lib) {
  fn_dgesdd = (LAPACKE_dgesdd_fn)dlsym(lib, "LAPACKE_dgesdd");
  fn_dpotrf = (LAPACKE_dpotrf_fn)dlsym(lib, "LAPACKE_dpotrf");
  fn_dgetrf = (LAPACKE_dgetrf_fn)dlsym(lib, "LAPACKE_dgetrf");
  fn_dgetrs = (LAPACKE_dgetrs_fn)dlsym(lib, "LAPACKE_dgetrs");
  fn_dtrsm  = (cblas_dtrsm_fn)   dlsym(lib, "cblas_dtrsm");
  fn_dgeqrf = (LAPACKE_dgeqrf_fn)dlsym(lib, "LAPACKE_dgeqrf");
  fn_dorgqr = (LAPACKE_dorgqr_fn)dlsym(lib, "LAPACKE_dorgqr");
  fn_dsyevd = (LAPACKE_dsyevd_fn)dlsym(lib, "LAPACKE_dsyevd");

  openblas_set_num_threads_fn set_threads =
      (openblas_set_num_threads_fn)dlsym(lib, "openblas_set_num_threads");
  if (set_threads) set_threads(1);
}

static void elodin_lapack_resolve_symbols(void) {
  if (fn_dgesdd) return;

#ifdef ELODIN_OPENBLAS_PATH
  {
#ifdef __APPLE__
    int dlopen_flags = RTLD_NOW | RTLD_LOCAL;
#else
    int dlopen_flags = RTLD_NOW | RTLD_LOCAL | RTLD_NODELETE | RTLD_DEEPBIND;
#endif
    void* lib = dlopen(ELODIN_OPENBLAS_PATH, dlopen_flags);
    if (lib) { elodin_lapack_load_from(lib); return; }
  }
#endif

  // Fallback: try standard library names (best-effort for development only).
  static const char* candidates[] = {
#ifdef __APPLE__
    "libopenblas.dylib",
#else
    "libopenblas.so.0", "libopenblas.so",
    "liblapack.so.3", "liblapack.so",
#endif
    NULL
  };
  for (int i = 0; candidates[i]; ++i) {
    void* lib = dlopen(candidates[i], RTLD_NOW | RTLD_LOCAL | RTLD_NODELETE);
    if (lib) { elodin_lapack_load_from(lib); return; }
  }

  // Last resort: global symbol table (Fortran symbols from scipy's OpenBLAS)
  fn_dgesdd = (LAPACKE_dgesdd_fn)dlsym(RTLD_DEFAULT, "LAPACKE_dgesdd");
  if (fn_dgesdd) {
    elodin_lapack_load_from(RTLD_DEFAULT);
  }
}

// LAPACKE layout constants
#define LAPACK_ROW_MAJOR 101
#define LAPACK_COL_MAJOR 102

// CBLAS constants for dtrsm
enum CBLAS_ORDER { CblasRowMajor = 101, CblasColMajor = 102 };
enum CBLAS_SIDE { CblasLeft = 141, CblasRight = 142 };
enum CBLAS_UPLO { CblasUpper = 121, CblasLower = 122 };
enum CBLAS_TRANSPOSE { CblasNoTrans = 111, CblasTrans = 112 };
enum CBLAS_DIAG { CblasNonUnit = 131, CblasUnit = 132 };

// --- ABI struct/shim definitions ---
// r, rr, rrr, rrrr already defined in shims.h. Only rrrrr is new.

IREE_VM_ABI_FIXED_STRUCT(rrrrr, {
  iree_vm_ref_t r0;
  iree_vm_ref_t r1;
  iree_vm_ref_t r2;
  iree_vm_ref_t r3;
  iree_vm_ref_t r4;
});

IREE_VM_ABI_DEFINE_SHIM(r, rr);
IREE_VM_ABI_DEFINE_SHIM(r, rrr);
IREE_VM_ABI_DEFINE_SHIM(r, rrrrr);
IREE_VM_ABI_DEFINE_SHIM(rr, rr);

// iree_vm_shim_rr_r is defined in IREE's shims.c (part of iree_modules_hal).
// Just declare it here so the function pointer table can reference it.
extern iree_status_t iree_vm_shim_rr_r(
    iree_vm_stack_t* IREE_RESTRICT stack,
    iree_vm_native_function_flags_t flags, iree_byte_span_t args_storage,
    iree_byte_span_t rets_storage,
    iree_vm_native_function_target2_t target_fn, void* IREE_RESTRICT module,
    void* IREE_RESTRICT module_state);

// --- Module state ---

typedef struct elodin_lapack_state_t {
  iree_hal_device_t* device;
  iree_allocator_t host_allocator;
} elodin_lapack_state_t;

// --- Helpers ---

// 64-byte alignment covers AVX-512 (64B), AVX2 (32B), and SSE (16B).
#define ELODIN_BUFFER_ALIGNMENT 64

static iree_status_t alloc_i32_scalar(
    iree_hal_device_t* device, int32_t value,
    iree_hal_buffer_view_t** out) {
  iree_hal_buffer_params_t p = {0};
  p.usage = IREE_HAL_BUFFER_USAGE_DEFAULT;
  p.access = IREE_HAL_MEMORY_ACCESS_ALL;
  p.type = IREE_HAL_MEMORY_TYPE_HOST_LOCAL | IREE_HAL_MEMORY_TYPE_DEVICE_VISIBLE;
  p.queue_affinity = IREE_HAL_QUEUE_AFFINITY_ANY;
  p.min_alignment = ELODIN_BUFFER_ALIGNMENT;
  return iree_hal_buffer_view_allocate_buffer_copy(
      device, iree_hal_device_allocator(device),
      0, NULL, IREE_HAL_ELEMENT_TYPE_SINT_32,
      IREE_HAL_ENCODING_TYPE_DENSE_ROW_MAJOR, p,
      iree_make_const_byte_span(&value, sizeof(int32_t)), out);
}

static iree_status_t alloc_i32_view(
    iree_hal_device_t* device,
    const iree_hal_dim_t* shape, iree_host_size_t rank,
    const int32_t* data, iree_host_size_t bytes,
    iree_hal_buffer_view_t** out) {
  iree_hal_buffer_params_t p = {0};
  p.usage = IREE_HAL_BUFFER_USAGE_DEFAULT;
  p.access = IREE_HAL_MEMORY_ACCESS_ALL;
  p.type = IREE_HAL_MEMORY_TYPE_HOST_LOCAL | IREE_HAL_MEMORY_TYPE_DEVICE_VISIBLE;
  p.queue_affinity = IREE_HAL_QUEUE_AFFINITY_ANY;
  p.min_alignment = ELODIN_BUFFER_ALIGNMENT;
  return iree_hal_buffer_view_allocate_buffer_copy(
      device, iree_hal_device_allocator(device),
      rank, shape, IREE_HAL_ELEMENT_TYPE_SINT_32,
      IREE_HAL_ENCODING_TYPE_DENSE_ROW_MAJOR, p,
      iree_make_const_byte_span(data, bytes), out);
}

static iree_status_t map_f64(iree_hal_buffer_view_t* v,
                             iree_hal_buffer_mapping_t* m, double** out) {
  IREE_RETURN_IF_ERROR(iree_hal_buffer_map_range(
      iree_hal_buffer_view_buffer(v), IREE_HAL_MAPPING_MODE_SCOPED,
      IREE_HAL_MEMORY_ACCESS_ALL, 0, IREE_HAL_WHOLE_BUFFER, m));
  *out = (double*)m->contents.data;
  return iree_ok_status();
}

// Allocate a HAL buffer, map it for read/write, and wrap as a buffer_view.
// The caller gets a writable host pointer to pass directly to LAPACK.
// The caller MUST call iree_hal_buffer_unmap_range(out_mapping) when done.
static iree_status_t alloc_f64_mapped(
    iree_hal_device_t* device,
    iree_allocator_t host_allocator,
    const iree_hal_dim_t* shape, iree_host_size_t rank,
    iree_host_size_t bytes,
    iree_hal_buffer_view_t** out_view,
    iree_hal_buffer_mapping_t* out_mapping,
    double** out_ptr) {
  iree_hal_buffer_params_t p = {0};
  p.usage = IREE_HAL_BUFFER_USAGE_DEFAULT;
  p.access = IREE_HAL_MEMORY_ACCESS_ALL;
  p.type = IREE_HAL_MEMORY_TYPE_HOST_LOCAL | IREE_HAL_MEMORY_TYPE_DEVICE_VISIBLE;
  p.queue_affinity = IREE_HAL_QUEUE_AFFINITY_ANY;
  p.min_alignment = ELODIN_BUFFER_ALIGNMENT;

  iree_hal_buffer_t* buf = NULL;
  IREE_RETURN_IF_ERROR(iree_hal_allocator_allocate_buffer(
      iree_hal_device_allocator(device), p,
      (iree_device_size_t)bytes, &buf));

  iree_status_t status = iree_hal_buffer_map_range(
      buf, IREE_HAL_MAPPING_MODE_SCOPED,
      IREE_HAL_MEMORY_ACCESS_ALL, 0, (iree_device_size_t)bytes, out_mapping);
  if (!iree_status_is_ok(status)) {
    iree_hal_buffer_release(buf);
    return status;
  }
  *out_ptr = (double*)out_mapping->contents.data;

  status = iree_hal_buffer_view_create(
      buf, rank, shape,
      IREE_HAL_ELEMENT_TYPE_FLOAT_64,
      IREE_HAL_ENCODING_TYPE_DENSE_ROW_MAJOR,
      host_allocator, out_view);
  if (!iree_status_is_ok(status)) {
    iree_hal_buffer_unmap_range(out_mapping);
    iree_hal_buffer_release(buf);
    return status;
  }
  iree_hal_buffer_release(buf);
  return status;
}

// Stack-or-heap allocation for small temporary buffers.
// Matrices <= 16x16 (2048 bytes) go on the stack; larger ones fall back to
// malloc. All customer workloads use matrices <= 6x6.
#define ELODIN_STACK_MAX_DOUBLES (16 * 16)
#define ELODIN_STACK_MAX_INTS 16

#define STACK_OR_HEAP_F64(name, count) \
    const size_t name##_count_ = (size_t)(count); \
    double name##_stack_[ELODIN_STACK_MAX_DOUBLES]; \
    int name##_on_heap_ = (name##_count_ > ELODIN_STACK_MAX_DOUBLES); \
    double* name = name##_on_heap_ \
        ? (double*)malloc(name##_count_ * sizeof(double)) : name##_stack_

#define STACK_OR_HEAP_I64(name, count) \
    const size_t name##_count_ = (size_t)(count); \
    lapack_int name##_stack_[ELODIN_STACK_MAX_INTS]; \
    int name##_on_heap_ = (name##_count_ > ELODIN_STACK_MAX_INTS); \
    lapack_int* name = name##_on_heap_ \
        ? (lapack_int*)malloc(name##_count_ * sizeof(lapack_int)) : name##_stack_

#define STACK_OR_HEAP_I32(name, count) \
    const size_t name##_count_ = (size_t)(count); \
    int32_t name##_stack_[ELODIN_STACK_MAX_INTS]; \
    int name##_on_heap_ = (name##_count_ > ELODIN_STACK_MAX_INTS); \
    int32_t* name = name##_on_heap_ \
        ? (int32_t*)malloc(name##_count_ * sizeof(int32_t)) : name##_stack_

#define STACK_FREE(name) \
    do { if (name##_on_heap_) free(name); } while(0)


#define VIEW_DIM(v, d) ((int)iree_hal_buffer_view_shape_dim((v), (d)))
#define VIEW_RANK(v) ((int)iree_hal_buffer_view_shape_rank((v)))


// =========================================================================
// dgesdd: SVD  (LAPACKE row-major API)
// Sig: (A[m,n]) -> (A_work[m,n], S[k], U[m,k], Vt[k,n], info scalar i32)
// Zero heap allocs: LAPACK writes directly into mapped HAL output buffers.
// =========================================================================

static iree_status_t elodin_lapack_dgesdd(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_r_t* IREE_RESTRICT args, iree_vm_abi_rrrrr_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* A = iree_hal_buffer_view_deref(args->r0);
  if (!A) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dgesdd: null");
  int m = VIEW_DIM(A, 0), n = VIEW_DIM(A, 1), k = m < n ? m : n;

  iree_status_t status = iree_ok_status();
  iree_hal_buffer_view_t *oa = NULL, *os = NULL, *ou = NULL, *ovt = NULL, *oi = NULL;
  iree_hal_buffer_mapping_t map_a, map_s, map_u, map_vt;
  double *a = NULL, *s = NULL, *u = NULL, *vt = NULL;
  int mapped_a = 0, mapped_s = 0, mapped_u = 0, mapped_vt = 0;

  iree_hal_dim_t sha[] = {m, n}, shs[] = {k}, shu[] = {m, k}, shvt[] = {k, n};

  status = alloc_f64_mapped(st->device, st->host_allocator, sha, 2, m*n*sizeof(double), &oa, &map_a, &a);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_a = 1;

  status = alloc_f64_mapped(st->device, st->host_allocator, shs, 1, k*sizeof(double), &os, &map_s, &s);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_s = 1;
  memset(s, 0, k * sizeof(double));

  status = alloc_f64_mapped(st->device, st->host_allocator, shu, 2, m*k*sizeof(double), &ou, &map_u, &u);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_u = 1;
  memset(u, 0, m * k * sizeof(double));

  status = alloc_f64_mapped(st->device, st->host_allocator, shvt, 2, k*n*sizeof(double), &ovt, &map_vt, &vt);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_vt = 1;
  memset(vt, 0, k * n * sizeof(double));

  { iree_hal_buffer_mapping_t am; double* asrc;
    status = map_f64(A, &am, &asrc);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, asrc, m * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }

  { lapack_int info = fn_dgesdd(LAPACK_ROW_MAJOR, 'S', m, n, a, n, s, u, k, vt, n);
    iree_hal_buffer_unmap_range(&map_a);  mapped_a = 0;
    iree_hal_buffer_unmap_range(&map_s);  mapped_s = 0;
    iree_hal_buffer_unmap_range(&map_u);  mapped_u = 0;
    iree_hal_buffer_unmap_range(&map_vt); mapped_vt = 0;
    status = alloc_i32_scalar(st->device, (int32_t)info, &oi);
    if (!iree_status_is_ok(status)) goto cleanup;
  }

  iree_vm_ref_wrap_assign(oa, iree_hal_buffer_view_type(), &rets->r0); oa = NULL;
  iree_vm_ref_wrap_assign(os, iree_hal_buffer_view_type(), &rets->r1); os = NULL;
  iree_vm_ref_wrap_assign(ou, iree_hal_buffer_view_type(), &rets->r2); ou = NULL;
  iree_vm_ref_wrap_assign(ovt, iree_hal_buffer_view_type(), &rets->r3); ovt = NULL;
  iree_vm_ref_wrap_assign(oi, iree_hal_buffer_view_type(), &rets->r4); oi = NULL;

cleanup:
  if (mapped_a)  iree_hal_buffer_unmap_range(&map_a);
  if (mapped_s)  iree_hal_buffer_unmap_range(&map_s);
  if (mapped_u)  iree_hal_buffer_unmap_range(&map_u);
  if (mapped_vt) iree_hal_buffer_unmap_range(&map_vt);
  if (oa) iree_hal_buffer_view_release(oa);
  if (os) iree_hal_buffer_view_release(os);
  if (ou) iree_hal_buffer_view_release(ou);
  if (ovt) iree_hal_buffer_view_release(ovt);
  if (oi) iree_hal_buffer_view_release(oi);
  return status;
}

// =========================================================================
// dpotrf: Cholesky (LAPACKE row-major API)
// Sig: (A[n,n]) -> (L[n,n], info scalar i32)
// Zero heap allocs: LAPACK writes directly into mapped HAL output buffer.
// =========================================================================

static iree_status_t elodin_lapack_dpotrf(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_r_t* IREE_RESTRICT args, iree_vm_abi_rr_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* A = iree_hal_buffer_view_deref(args->r0);
  if (!A) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dpotrf: null");
  int n = VIEW_DIM(A, 0);

  iree_status_t status = iree_ok_status();
  iree_hal_buffer_view_t *ol = NULL, *oi = NULL;
  iree_hal_buffer_mapping_t map_l;
  double* a = NULL;
  int mapped_l = 0;

  iree_hal_dim_t sh[] = {n, n};
  status = alloc_f64_mapped(st->device, st->host_allocator, sh, 2, n*n*sizeof(double), &ol, &map_l, &a);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_l = 1;

  { iree_hal_buffer_mapping_t am; double* as;
    status = map_f64(A, &am, &as);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, as, n * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }

  { lapack_int info = fn_dpotrf(LAPACK_ROW_MAJOR, 'L', n, a, n);
    for (int i = 0; i < n; ++i)
      for (int j = i + 1; j < n; ++j)
        a[i * n + j] = 0.0;
    iree_hal_buffer_unmap_range(&map_l); mapped_l = 0;
    status = alloc_i32_scalar(st->device, (int32_t)info, &oi);
    if (!iree_status_is_ok(status)) goto cleanup;
  }

  iree_vm_ref_wrap_assign(ol, iree_hal_buffer_view_type(), &rets->r0); ol = NULL;
  iree_vm_ref_wrap_assign(oi, iree_hal_buffer_view_type(), &rets->r1); oi = NULL;

cleanup:
  if (mapped_l) iree_hal_buffer_unmap_range(&map_l);
  if (ol) iree_hal_buffer_view_release(ol);
  if (oi) iree_hal_buffer_view_release(oi);
  return status;
}

// =========================================================================
// dgetrf: LU factorization (LAPACKE row-major API)
// Sig: (A[m,n]) -> (LU[m,n], pivots[k]i32, info scalar i32)
// LAPACK writes LU directly into mapped HAL buffer; pivots use stack alloc.
// =========================================================================

static iree_status_t elodin_lapack_dgetrf(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_r_t* IREE_RESTRICT args, iree_vm_abi_rrr_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* A = iree_hal_buffer_view_deref(args->r0);
  if (!A) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dgetrf: null");
  int m = VIEW_DIM(A, 0), n = VIEW_DIM(A, 1), k = m < n ? m : n;

  iree_status_t status = iree_ok_status();
  STACK_OR_HEAP_I64(ipiv, k);
  STACK_OR_HEAP_I32(piv32, k);
  iree_hal_buffer_view_t *olu = NULL, *op = NULL, *oi = NULL;
  iree_hal_buffer_mapping_t map_lu;
  double* a = NULL;
  int mapped_lu = 0;

  if (!ipiv || !piv32) {
    status = iree_make_status(IREE_STATUS_RESOURCE_EXHAUSTED, "dgetrf: alloc");
    goto cleanup;
  }

  iree_hal_dim_t shlu[] = {m, n};
  status = alloc_f64_mapped(st->device, st->host_allocator, shlu, 2, m*n*sizeof(double), &olu, &map_lu, &a);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_lu = 1;

  { iree_hal_buffer_mapping_t am; double* as;
    status = map_f64(A, &am, &as);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, as, m * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }

  { lapack_int info = fn_dgetrf(LAPACK_ROW_MAJOR, m, n, a, n, ipiv);
    iree_hal_buffer_unmap_range(&map_lu); mapped_lu = 0;
    for (int i = 0; i < k; ++i) piv32[i] = (int32_t)(ipiv[i] - 1);
    iree_hal_dim_t shp[] = {k};
    status = alloc_i32_view(st->device, shp, 1, piv32, k*sizeof(int32_t), &op);
    if (!iree_status_is_ok(status)) goto cleanup;
    status = alloc_i32_scalar(st->device, (int32_t)info, &oi);
    if (!iree_status_is_ok(status)) goto cleanup;
  }

  iree_vm_ref_wrap_assign(olu, iree_hal_buffer_view_type(), &rets->r0); olu = NULL;
  iree_vm_ref_wrap_assign(op, iree_hal_buffer_view_type(), &rets->r1); op = NULL;
  iree_vm_ref_wrap_assign(oi, iree_hal_buffer_view_type(), &rets->r2); oi = NULL;

cleanup:
  if (mapped_lu) iree_hal_buffer_unmap_range(&map_lu);
  STACK_FREE(ipiv);
  STACK_FREE(piv32);
  if (olu) iree_hal_buffer_view_release(olu);
  if (op) iree_hal_buffer_view_release(op);
  if (oi) iree_hal_buffer_view_release(oi);
  return status;
}

// =========================================================================
// dgeqrf: QR factorization (LAPACKE row-major API)
// Sig: (A[m,n]) -> (householder[m,n], tau[k])
// Zero heap allocs: LAPACK writes directly into mapped HAL output buffers.
// =========================================================================

static iree_status_t elodin_lapack_dgeqrf(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_r_t* IREE_RESTRICT args, iree_vm_abi_rr_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* A = iree_hal_buffer_view_deref(args->r0);
  if (!A) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dgeqrf: null");
  int m = VIEW_DIM(A, 0), n = VIEW_DIM(A, 1), k = m < n ? m : n;

  iree_status_t status = iree_ok_status();
  iree_hal_buffer_view_t *oh = NULL, *ot = NULL;
  iree_hal_buffer_mapping_t map_h, map_t;
  double *a = NULL, *tau = NULL;
  int mapped_h = 0, mapped_t = 0;

  iree_hal_dim_t shh[] = {m, n}, sht[] = {k};

  status = alloc_f64_mapped(st->device, st->host_allocator, shh, 2, m*n*sizeof(double), &oh, &map_h, &a);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_h = 1;

  status = alloc_f64_mapped(st->device, st->host_allocator, sht, 1, k*sizeof(double), &ot, &map_t, &tau);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_t = 1;
  memset(tau, 0, k * sizeof(double));

  { iree_hal_buffer_mapping_t am; double* as;
    status = map_f64(A, &am, &as);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, as, m * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }

  { lapack_int info = fn_dgeqrf(LAPACK_ROW_MAJOR, m, n, a, n, tau);
    if (info != 0) {
      memset(a, 0, m * n * sizeof(double));
      memset(tau, 0, k * sizeof(double));
    }
  }

  iree_hal_buffer_unmap_range(&map_h); mapped_h = 0;
  iree_hal_buffer_unmap_range(&map_t); mapped_t = 0;

  iree_vm_ref_wrap_assign(oh, iree_hal_buffer_view_type(), &rets->r0); oh = NULL;
  iree_vm_ref_wrap_assign(ot, iree_hal_buffer_view_type(), &rets->r1); ot = NULL;

cleanup:
  if (mapped_h) iree_hal_buffer_unmap_range(&map_h);
  if (mapped_t) iree_hal_buffer_unmap_range(&map_t);
  if (oh) iree_hal_buffer_view_release(oh);
  if (ot) iree_hal_buffer_view_release(ot);
  return status;
}

// =========================================================================
// dorgqr: Generate Q from Householder reflectors (LAPACKE row-major API)
// Sig: (householder[m,n], tau[k]) -> Q[m,k]
// Uses stack alloc for working buffers; extracts Q directly into mapped HAL.
// =========================================================================

static iree_status_t elodin_lapack_dorgqr(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_rr_t* IREE_RESTRICT args, iree_vm_abi_r_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* HH = iree_hal_buffer_view_deref(args->r0);
  iree_hal_buffer_view_t* TAU = iree_hal_buffer_view_deref(args->r1);
  if (!HH || !TAU) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dorgqr: null");
  int m = VIEW_DIM(HH, 0), n = VIEW_DIM(HH, 1), k = m < n ? m : n;

  iree_status_t status = iree_ok_status();
  STACK_OR_HEAP_F64(a, m * n);
  STACK_OR_HEAP_F64(tau, k);
  iree_hal_buffer_view_t* oq = NULL;
  iree_hal_buffer_mapping_t map_q;
  double* q = NULL;
  int mapped_q = 0;

  if (!a || !tau) {
    status = iree_make_status(IREE_STATUS_RESOURCE_EXHAUSTED, "dorgqr: alloc");
    goto cleanup;
  }

  { iree_hal_buffer_mapping_t hm; double* hs;
    status = map_f64(HH, &hm, &hs);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, hs, m * n * sizeof(double));
    iree_hal_buffer_unmap_range(&hm);
  }
  { iree_hal_buffer_mapping_t tm; double* ts;
    status = map_f64(TAU, &tm, &ts);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(tau, ts, k * sizeof(double));
    iree_hal_buffer_unmap_range(&tm);
  }

  fn_dorgqr(LAPACK_ROW_MAJOR, m, k, k, a, n, tau);

  iree_hal_dim_t shq[] = {m, k};
  status = alloc_f64_mapped(st->device, st->host_allocator, shq, 2, m*k*sizeof(double), &oq, &map_q, &q);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_q = 1;

  for (int i = 0; i < m; ++i)
    for (int j = 0; j < k; ++j)
      q[i * k + j] = a[i * n + j];

  iree_hal_buffer_unmap_range(&map_q); mapped_q = 0;

  iree_vm_ref_wrap_assign(oq, iree_hal_buffer_view_type(), &rets->r0); oq = NULL;

cleanup:
  if (mapped_q) iree_hal_buffer_unmap_range(&map_q);
  STACK_FREE(a);
  STACK_FREE(tau);
  if (oq) iree_hal_buffer_view_release(oq);
  return status;
}

// =========================================================================
// dtrsm: Triangular solve (CBLAS row-major API)
// Sig: (A[n,n], B) -> X
// Same transpose convention as dgetrs: rank-2 B arrives transposed from
// the compiler.  Always transpose back for CBLAS, transpose result to match.
// Uses stack alloc for working buffers; writes output into mapped HAL.
// =========================================================================

static iree_status_t elodin_lapack_dtrsm(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_rr_t* IREE_RESTRICT args, iree_vm_abi_r_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* VA = iree_hal_buffer_view_deref(args->r0);
  iree_hal_buffer_view_t* VB = iree_hal_buffer_view_deref(args->r1);
  if (!VA || !VB) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dtrsm: null");

  int n = VIEW_DIM(VA, 0);
  int b_rank = VIEW_RANK(VB);
  int matrix_rhs = (b_rank >= 2);
  int nrhs = matrix_rhs ? VIEW_DIM(VB, 0) : 1;

  iree_status_t status = iree_ok_status();
  STACK_OR_HEAP_F64(a, n * n);
  STACK_OR_HEAP_F64(b, n * nrhs);
  iree_hal_buffer_view_t* ox = NULL;
  iree_hal_buffer_mapping_t map_x;
  double* xptr = NULL;
  int mapped_x = 0;

  if (!a || !b) {
    status = iree_make_status(IREE_STATUS_RESOURCE_EXHAUSTED, "dtrsm: alloc");
    goto cleanup;
  }

  { iree_hal_buffer_mapping_t am; double* as;
    status = map_f64(VA, &am, &as);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, as, n * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }
  { iree_hal_buffer_mapping_t bm; double* bs;
    status = map_f64(VB, &bm, &bs);
    if (!iree_status_is_ok(status)) goto cleanup;
    if (matrix_rhs) {
      for (int i = 0; i < n; ++i)
        for (int j = 0; j < nrhs; ++j)
          b[i * nrhs + j] = bs[j * n + i];
    } else {
      memcpy(b, bs, n * sizeof(double));
    }
    iree_hal_buffer_unmap_range(&bm);
  }

  { int ldb = matrix_rhs ? nrhs : 1;
    fn_dtrsm(CblasRowMajor, CblasLeft, CblasLower, CblasNoTrans, CblasNonUnit,
             n, nrhs, 1.0, a, n, b, ldb);
  }

  if (matrix_rhs) {
    iree_hal_dim_t sh_t[] = {(iree_hal_dim_t)nrhs, (iree_hal_dim_t)n};
    status = alloc_f64_mapped(st->device, st->host_allocator, sh_t, 2, nrhs*n*sizeof(double), &ox, &map_x, &xptr);
    if (!iree_status_is_ok(status)) goto cleanup;
    mapped_x = 1;
    for (int i = 0; i < nrhs; ++i)
      for (int j = 0; j < n; ++j)
        xptr[i * n + j] = b[j * nrhs + i];
    iree_hal_buffer_unmap_range(&map_x); mapped_x = 0;
  } else {
    iree_hal_dim_t sh1[] = {(iree_hal_dim_t)n};
    status = alloc_f64_mapped(st->device, st->host_allocator, sh1, 1, n*sizeof(double), &ox, &map_x, &xptr);
    if (!iree_status_is_ok(status)) goto cleanup;
    mapped_x = 1;
    memcpy(xptr, b, n * sizeof(double));
    iree_hal_buffer_unmap_range(&map_x); mapped_x = 0;
  }

  iree_vm_ref_wrap_assign(ox, iree_hal_buffer_view_type(), &rets->r0); ox = NULL;

cleanup:
  if (mapped_x) iree_hal_buffer_unmap_range(&map_x);
  STACK_FREE(a);
  STACK_FREE(b);
  if (ox) iree_hal_buffer_view_release(ox);
  return status;
}

// =========================================================================
// dsyevd: Symmetric eigendecomposition (LAPACKE row-major API)
// Sig: (A[n,n]) -> (eigvecs[n,n], eigvals[n], info scalar i32)
// Zero heap allocs: LAPACK writes directly into mapped HAL output buffers.
// =========================================================================

static iree_status_t elodin_lapack_dsyevd(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_r_t* IREE_RESTRICT args, iree_vm_abi_rrr_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* A = iree_hal_buffer_view_deref(args->r0);
  if (!A) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dsyevd: null");
  int n = VIEW_DIM(A, 0);

  iree_status_t status = iree_ok_status();
  iree_hal_buffer_view_t *ov = NULL, *ow = NULL, *oi = NULL;
  iree_hal_buffer_mapping_t map_v, map_w;
  double *a = NULL, *w = NULL;
  int mapped_v = 0, mapped_w = 0;

  iree_hal_dim_t shv[] = {n, n}, shw[] = {n};

  status = alloc_f64_mapped(st->device, st->host_allocator, shv, 2, n*n*sizeof(double), &ov, &map_v, &a);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_v = 1;

  status = alloc_f64_mapped(st->device, st->host_allocator, shw, 1, n*sizeof(double), &ow, &map_w, &w);
  if (!iree_status_is_ok(status)) goto cleanup;
  mapped_w = 1;
  memset(w, 0, n * sizeof(double));

  { iree_hal_buffer_mapping_t am; double* as;
    status = map_f64(A, &am, &as);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, as, n * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }

  { lapack_int info = fn_dsyevd(LAPACK_ROW_MAJOR, 'V', 'L', n, a, n, w);
    iree_hal_buffer_unmap_range(&map_v); mapped_v = 0;
    iree_hal_buffer_unmap_range(&map_w); mapped_w = 0;
    status = alloc_i32_scalar(st->device, (int32_t)info, &oi);
    if (!iree_status_is_ok(status)) goto cleanup;
  }

  iree_vm_ref_wrap_assign(ov, iree_hal_buffer_view_type(), &rets->r0); ov = NULL;
  iree_vm_ref_wrap_assign(ow, iree_hal_buffer_view_type(), &rets->r1); ow = NULL;
  iree_vm_ref_wrap_assign(oi, iree_hal_buffer_view_type(), &rets->r2); oi = NULL;

cleanup:
  if (mapped_v) iree_hal_buffer_unmap_range(&map_v);
  if (mapped_w) iree_hal_buffer_unmap_range(&map_w);
  if (ov) iree_hal_buffer_view_release(ov);
  if (ow) iree_hal_buffer_view_release(ow);
  if (oi) iree_hal_buffer_view_release(oi);
  return status;
}

// =========================================================================
// dgetrs: Linear solve via LU (LAPACKE row-major API)
// Sig: (A[n,n], B) -> (X, info scalar i32)
// All rank-2 B arrives transposed from the compiler's rewriteSolvePattern
// (B_t = transpose(B_orig)).  We always transpose it back for LAPACK and
// transpose the result to match.  The double-transpose (compiler + here)
// cancels out, producing correct A^{-1} * B_orig for any B.
// Uses stack alloc for working buffers; writes output into mapped HAL.
// =========================================================================

static iree_status_t elodin_lapack_dgetrs(
    iree_vm_stack_t* IREE_RESTRICT stack, void* IREE_RESTRICT mod,
    elodin_lapack_state_t* IREE_RESTRICT st,
    iree_vm_abi_rr_t* IREE_RESTRICT args, iree_vm_abi_rr_t* IREE_RESTRICT rets) {
  iree_hal_buffer_view_t* VA = iree_hal_buffer_view_deref(args->r0);
  iree_hal_buffer_view_t* VB = iree_hal_buffer_view_deref(args->r1);
  if (!VA || !VB) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "dgetrs: null");
  int n = VIEW_DIM(VA, 0);
  int b_rank = VIEW_RANK(VB);
  int matrix_rhs = (b_rank >= 2);
  int nrhs = matrix_rhs ? VIEW_DIM(VB, 0) : 1;

  iree_status_t status = iree_ok_status();
  STACK_OR_HEAP_F64(a, n * n);
  STACK_OR_HEAP_F64(b, n * nrhs);
  STACK_OR_HEAP_I64(ipiv, n);
  iree_hal_buffer_view_t *ox = NULL, *oi = NULL;
  iree_hal_buffer_mapping_t map_x;
  double* xptr = NULL;
  int mapped_x = 0;

  if (!a || !b || !ipiv) {
    status = iree_make_status(IREE_STATUS_RESOURCE_EXHAUSTED, "dgetrs: alloc");
    goto cleanup;
  }

  { iree_hal_buffer_mapping_t am; double* as;
    status = map_f64(VA, &am, &as);
    if (!iree_status_is_ok(status)) goto cleanup;
    memcpy(a, as, n * n * sizeof(double));
    iree_hal_buffer_unmap_range(&am);
  }
  { iree_hal_buffer_mapping_t bm; double* bs;
    status = map_f64(VB, &bm, &bs);
    if (!iree_status_is_ok(status)) goto cleanup;
    if (matrix_rhs) {
      for (int i = 0; i < n; ++i)
        for (int j = 0; j < nrhs; ++j)
          b[i * nrhs + j] = bs[j * n + i];
    } else {
      memcpy(b, bs, n * sizeof(double));
    }
    iree_hal_buffer_unmap_range(&bm);
  }

  { int ldb = matrix_rhs ? nrhs : 1;
    lapack_int info = fn_dgetrf(LAPACK_ROW_MAJOR, n, n, a, n, ipiv);
    if (info >= 0) {
      lapack_int info2 = fn_dgetrs(LAPACK_ROW_MAJOR, 'N', n, nrhs, a, n, ipiv, b, ldb);
      if (info2 < 0) {
        for (int i = 0; i < n * nrhs; ++i) b[i] = NAN;
      }
    } else {
      for (int i = 0; i < n * nrhs; ++i) b[i] = NAN;
    }

    if (matrix_rhs) {
      iree_hal_dim_t sh_t[] = {(iree_hal_dim_t)nrhs, (iree_hal_dim_t)n};
      status = alloc_f64_mapped(st->device, st->host_allocator, sh_t, 2, nrhs*n*sizeof(double), &ox, &map_x, &xptr);
      if (!iree_status_is_ok(status)) goto cleanup;
      mapped_x = 1;
      for (int i = 0; i < nrhs; ++i)
        for (int j = 0; j < n; ++j)
          xptr[i * n + j] = b[j * nrhs + i];
      iree_hal_buffer_unmap_range(&map_x); mapped_x = 0;
    } else {
      iree_hal_dim_t sh1[] = {(iree_hal_dim_t)n};
      status = alloc_f64_mapped(st->device, st->host_allocator, sh1, 1, n*sizeof(double), &ox, &map_x, &xptr);
      if (!iree_status_is_ok(status)) goto cleanup;
      mapped_x = 1;
      memcpy(xptr, b, n * sizeof(double));
      iree_hal_buffer_unmap_range(&map_x); mapped_x = 0;
    }

    status = alloc_i32_scalar(st->device, (int32_t)info, &oi);
    if (!iree_status_is_ok(status)) goto cleanup;
  }

  iree_vm_ref_wrap_assign(ox, iree_hal_buffer_view_type(), &rets->r0); ox = NULL;
  iree_vm_ref_wrap_assign(oi, iree_hal_buffer_view_type(), &rets->r1); oi = NULL;

cleanup:
  if (mapped_x) iree_hal_buffer_unmap_range(&map_x);
  STACK_FREE(a);
  STACK_FREE(b);
  STACK_FREE(ipiv);
  if (ox) iree_hal_buffer_view_release(ox);
  if (oi) iree_hal_buffer_view_release(oi);
  return status;
}

// =========================================================================
// Module descriptor
// One export per routine (alphabetically sorted for IREE VM binary search).
// The compiler generates shape-suffixed names (e.g. "dgesdd_6_6"); the
// custom lookup_function below strips suffixes so any size resolves here.
// =========================================================================

static const iree_vm_native_export_descriptor_t elodin_lapack_exports_[] = {
    {IREE_SVL("dgeqrf"), IREE_SVL("0r_rr"), 0, NULL},
    {IREE_SVL("dgesdd"), IREE_SVL("0r_rrrrr"), 0, NULL},
    {IREE_SVL("dgetrf"), IREE_SVL("0r_rrr"), 0, NULL},
    {IREE_SVL("dgetrs"), IREE_SVL("0rr_rr"), 0, NULL},
    {IREE_SVL("dorgqr"), IREE_SVL("0rr_r"), 0, NULL},
    {IREE_SVL("dpotrf"), IREE_SVL("0r_rr"), 0, NULL},
    {IREE_SVL("dsyevd"), IREE_SVL("0r_rrr"), 0, NULL},
    {IREE_SVL("dtrsm"),  IREE_SVL("0rr_r"), 0, NULL},
};

#define F(shim, target) \
    {(iree_vm_native_function_shim_t)(shim), \
     (iree_vm_native_function_target_t)(target)}

static const iree_vm_native_function_ptr_t elodin_lapack_funcs_[] = {
    F(iree_vm_shim_r_rr,    elodin_lapack_dgeqrf),
    F(iree_vm_shim_r_rrrrr, elodin_lapack_dgesdd),
    F(iree_vm_shim_r_rrr,   elodin_lapack_dgetrf),
    F(iree_vm_shim_rr_rr,   elodin_lapack_dgetrs),
    F(iree_vm_shim_rr_r,    elodin_lapack_dorgqr),
    F(iree_vm_shim_r_rr,    elodin_lapack_dpotrf),
    F(iree_vm_shim_r_rrr,   elodin_lapack_dsyevd),
    F(iree_vm_shim_rr_r,    elodin_lapack_dtrsm),
};

static const iree_vm_native_module_descriptor_t elodin_lapack_descriptor_ = {
    .name = IREE_SVL("elodin_lapack"),
    .version = 0,
    .attr_count = 0, .attrs = NULL,
    .dependency_count = 0, .dependencies = NULL,
    .import_count = 0, .imports = NULL,
    .export_count = sizeof(elodin_lapack_exports_) / sizeof(elodin_lapack_exports_[0]),
    .exports = elodin_lapack_exports_,
    .function_count = sizeof(elodin_lapack_funcs_) / sizeof(elodin_lapack_funcs_[0]),
    .functions = elodin_lapack_funcs_,
};

// =========================================================================
// Dynamic lookup: strip dimension suffixes so any matrix size resolves
// to the base routine (e.g. "dgetrs_2_2_2" -> "dgetrs").
// =========================================================================

static iree_status_t (*elodin_lapack_original_lookup)(
    void* self, iree_vm_function_linkage_t linkage, iree_string_view_t name,
    const iree_vm_function_signature_t* expected_signature,
    iree_vm_function_t* out_function) = NULL;

static iree_status_t elodin_lapack_lookup_function(
    void* self, iree_vm_function_linkage_t linkage, iree_string_view_t name,
    const iree_vm_function_signature_t* expected_signature,
    iree_vm_function_t* out_function) {
  iree_status_t status = elodin_lapack_original_lookup(
      self, linkage, name, expected_signature, out_function);
  if (iree_status_is_ok(status)) return status;
  iree_status_ignore(status);

  iree_host_size_t base_len = name.size;
  for (iree_host_size_t i = 0; i < name.size; i++) {
    if (name.data[i] == '_' && i + 1 < name.size &&
        name.data[i + 1] >= '0' && name.data[i + 1] <= '9') {
      base_len = i;
      break;
    }
  }
  if (base_len == name.size) {
    return iree_make_status(IREE_STATUS_NOT_FOUND,
        "elodin_lapack: unknown function '%.*s'",
        (int)name.size, name.data);
  }

  iree_string_view_t base_name = iree_make_string_view(name.data, base_len);
  return elodin_lapack_original_lookup(
      self, linkage, base_name, /*expected_signature=*/NULL, out_function);
}

// --- Module lifecycle ---

typedef struct elodin_lapack_module_t {
  iree_allocator_t host_allocator;
  iree_hal_device_t* device;
} elodin_lapack_module_t;

static iree_status_t elodin_lapack_alloc_state(
    void* self, iree_allocator_t alloc, iree_vm_module_state_t** out) {
  elodin_lapack_module_t* m = (elodin_lapack_module_t*)self;
  elodin_lapack_state_t* s = NULL;
  IREE_RETURN_IF_ERROR(iree_allocator_malloc(alloc, sizeof(*s), (void**)&s));
  memset(s, 0, sizeof(*s));
  s->device = m->device;
  iree_hal_device_retain(s->device);
  s->host_allocator = alloc;
  *out = (iree_vm_module_state_t*)s;
  return iree_ok_status();
}

static void elodin_lapack_free_state(void* self, iree_vm_module_state_t* state) {
  elodin_lapack_state_t* s = (elodin_lapack_state_t*)state;
  if (s->device) iree_hal_device_release(s->device);
  iree_allocator_free(((elodin_lapack_module_t*)self)->host_allocator, s);
}

static void elodin_lapack_destroy(void* self) {
  elodin_lapack_module_t* mod = (elodin_lapack_module_t*)self;
  if (mod->device) iree_hal_device_release(mod->device);
  free(mod);
}

iree_status_t elodin_lapack_module_create(
    iree_vm_instance_t* instance, iree_hal_device_t* device,
    iree_allocator_t alloc, iree_vm_module_t** out_module) {
  if (!out_module) return iree_make_status(IREE_STATUS_INVALID_ARGUMENT, "null");
  *out_module = NULL;

  elodin_lapack_resolve_symbols();
  if (!fn_dgesdd || !fn_dpotrf || !fn_dgetrf || !fn_dgetrs ||
      !fn_dtrsm  || !fn_dgeqrf || !fn_dorgqr || !fn_dsyevd) {
    return iree_make_status(IREE_STATUS_UNAVAILABLE,
        "LAPACK symbols not found (no OpenBLAS loaded in process)");
  }

  elodin_lapack_module_t* mod =
      (elodin_lapack_module_t*)calloc(1, sizeof(elodin_lapack_module_t));
  if (!mod) {
    return iree_make_status(IREE_STATUS_RESOURCE_EXHAUSTED,
        "elodin_lapack: module alloc failed");
  }
  mod->host_allocator = alloc;
  mod->device = device;
  iree_hal_device_retain(device);

  iree_vm_module_t iface;
  iree_status_t status = iree_vm_module_initialize(&iface, mod);
  if (!iree_status_is_ok(status)) { iree_hal_device_release(device); free(mod); return status; }
  iface.alloc_state = elodin_lapack_alloc_state;
  iface.free_state = elodin_lapack_free_state;
  iface.destroy = elodin_lapack_destroy;

  status = iree_vm_native_module_create(
      &iface, &elodin_lapack_descriptor_, instance, alloc, out_module);
  if (!iree_status_is_ok(status)) { iree_hal_device_release(device); free(mod); return status; }

  elodin_lapack_original_lookup = (*out_module)->lookup_function;
  (*out_module)->lookup_function = elodin_lapack_lookup_function;
  return iree_ok_status();
}
