// elodin_lapack VM module: provides LAPACK functions to IREE via OpenBLAS.
//
// Creates and registers a VM module named "elodin_lapack" that exports
// functions matching the signatures generated by the compiler patch in
// StableHLOCustomCalls.cpp.

#ifndef ELODIN_LAPACK_MODULE_H
#define ELODIN_LAPACK_MODULE_H

#include "iree/vm/api.h"
#include "iree/hal/api.h"

#ifdef __cplusplus
extern "C" {
#endif

// Creates the elodin_lapack VM module.
// The module must be appended to a session before loading a VMFB that
// imports elodin_lapack functions.
iree_status_t elodin_lapack_module_create(
    iree_vm_instance_t* instance,
    iree_hal_device_t* device,
    iree_allocator_t host_allocator,
    iree_vm_module_t** out_module);

#ifdef __cplusplus
}
#endif

#endif  // ELODIN_LAPACK_MODULE_H
