apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

replicas:
- name: sim-runner-balloon
  count: 4

patches:
- target:
    kind: Ingress
    name: elodin
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: app.elodin.systems
- target:
    namespace: elodin-app
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: elodin-app-prod
- target:
    kind: Namespace
    name: elodin-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-app-prod
- target:
    kind: Namespace
    name: elodin-vms
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-vms-prod
- target:
    namespace: elodin-vms
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: elodin-vms-prod
- target:
    kind: RoleBinding
    name: elo-atc
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: elodin-app-prod


configMapGenerator:
- name: elo-atc-config
  namespace: elodin-app
  files:
  - atc.toml=elo-atc-config.toml
- name: elo-dashboard
  namespace: elodin-app
  literals:
  - PHX_HOST=app.elodin.systems
  - RELEASE_COOKIE=dummy_cookie
  - SECRET_KEY_BASE=pvS+BSCE9uyDsYR3d4A/vENpQj/0OtpzR+N/FAY1+yQD1OfS8Adp2nh537rzSEb0
  - ATC_INTERNAL_ADDR=elo-atc.elodin-app-prod.svc.cluster.local:50051
  - ATC_ADDR=app.elodin.systems
  - AUTH_BASE_URL=https://auth.elodin.systems

secretGenerator:
- name: elo-dashboard-secret
  namespace: elodin-app
  envs:
  - elo-dashboard-secret.env

images:
- name: elodin-infra/elo-atc
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-atc/x86_64
  newTag: $RELEASE_IMAGE_TAG
- name: elodin-infra/elo-dashboard
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-dashboard/x86_64
  newTag: $RELEASE_IMAGE_TAG
- name: elodin-infra/elo-sim-runner
  newName: us-central1-docker.pkg.dev/elodin-infra/elo-sim-runner/x86_64
  newTag: $RELEASE_IMAGE_TAG
