apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patches:
- target:
    kind: Ingress
    name: elodin
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: elodin.app
- target:
    kind: Service
    name: traefik-web-service
  patch: |-
    - op: replace
      path: /spec/loadBalancerIP
      value: 35.239.39.199
- target:
    namespace: elodin-app
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: elodin-app-prod
- target:
    kind: Namespace
    name: elodin-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-app-prod
- target:
    kind: Namespace
    name: elodin-vms
  patch: |-
    - op: replace
      path: /metadata/name
      value: elodin-vms-prod


configMapGenerator:
- name: elo-atc-config
  namespace: elodin-app
  files:
  - atc.toml=elo-atc-config.toml
- name: elo-dashboard
  namespace: elodin-app
  literals:
  - PHX_HOST=elodin.app
  - RELEASE_COOKIE=dummy_cookie
  - SECRET_KEY_BASE=pvS+BSCE9uyDsYR3d4A/vENpQj/0OtpzR+N/FAY1+yQD1OfS8Adp2nh537rzSEb0
  - ATC_INTERNAL_ADDR=elo-atc.elodin-app-prod.svc.cluster.local:50051
  - ATC_ADDR=elodin.app
  - AUTH_BASE_URL=https://auth.elodin.app

secretGenerator:
- name: elo-dashboard-secret
  namespace: elodin-app
  envs:
  - elo-dashboard-secret.env

images:
- name: elodin-dev/elo-atc
  newName: us-central1-docker.pkg.dev/elodin-dev/elo-atc/x86_64
  newTag: 0.1.5
- name: elodin-dev/elo-dashboard
  newName: us-central1-docker.pkg.dev/elodin-dev/elo-dashboard/x86_64
  newTag: 0.1.8
