"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of solar-system-template.kdl.
"""

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.tabs(
            ui.hsplit(
                ui.tabs(
                    ui.viewport(
                        name="SolarSystem",
                        fov=45.0,
                        active=True,
                        show_grid=True,
                        show_arrows=True,
                        create_frustum=False,
                        show_frustums=False,
                        frustums_color="yellow",
                        projection_color="white",
                        frustums_thickness=0.006,
                        show_view_cube=True,
                        effects=True,
                        hdr=True,
                        cinematic=False,
                        pos="(0,0,0,1, -6,6,6)",
                        look_at="(0,0,0,1, 0,0,0)",
                        smoothing=0.0,
                    ),
                    ui.viewport(
                        name="TopDown",
                        fov=45.0,
                        active=False,
                        show_grid=True,
                        show_arrows=True,
                        create_frustum=False,
                        show_frustums=False,
                        frustums_color="yellow",
                        projection_color="white",
                        frustums_thickness=0.006,
                        show_view_cube=True,
                        effects=True,
                        hdr=True,
                        cinematic=False,
                        pos="(0,0,0,1, 0,0,25)",
                        look_at="(0,0,0,1, 0,0,0)",
                        smoothing=0.0,
                    ),
                    share=0.75,
                ),
                ui.tabs(
                    ui.graph(
                        "earth.world_pos[4],earth.world_pos[5],earth.world_pos[6],truth_earth.truth_world_pos[4],truth_earth.truth_world_pos[5],truth_earth.truth_world_pos[6]",
                        name="Earth vs Truth (AU)",
                    ),
                    ui.hierarchy(),
                    ui.inspector(),
                    share=0.25,
                ),
            ),
        ),
        coordinate=ui.coordinate(
            frame="ENU",
        ),
        timeline=ui.timeline(
            played_color="yalk",
            future_color="white",
            follow_latest=True,
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
