[build]
target = "index.html"
dist = "dist"
# Debug wasm is ~500MB and never finishes compiling in the browser.
cargo_profile = "wasm-release"

[watch]
watch = [".", "../../libs/elodin-editor", "../../libs/impeller"]

[serve]
port = 8080
addresses = ["127.0.0.1"]
no_autoreload = true
