[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg=web_sys_unstable_apis",
  "--cfg=getrandom_backend=\"wasm_js\"",
]

[alias]
elodin = "run --bin elodin"
elodin-db = "run --bin elodin-db"
