direction: right

fsw: Flight Software {
  orchestrator: Orchestrator
  control_systems: Control Systems {
    style.multiple: true
  }
  orchestrator -> control_systems
}

systems: Systems {
  ne_systems: Non-effector Systems {
    style.multiple: true
  }
  6dof: 6-DOF {
    effectors: Effectors {
      style.multiple: true
    }
  }
  integrator: Integrator
  ne_systems -> 6dof -> integrator
}

world: World {
  entities: Entities {
    style.multiple: true
  }
}

simulation: Simulation

systems -> simulation
world -> simulation

fsw <-> simulation: conduit {
  style {
    stroke: red
    font-color: red
    bold: true
    stroke-width: 4
  }
}
