[package]
name = "atc"
version = "0.1.0"
edition = "2021"
metadata.dist.dist = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async
tokio.version = "1.34"
tokio.features = ["full"]
tokio-util.version = "0.7"
tokio-util.features = ["codec"]

# types
elodin-types.path = "../../libs/elodin-types/rust"
uuid.version = "1.6.1"
uuid.features = ["fast-rng", "v7"]

# logs
tracing = "0.1"
tracing-subscriber.version = "0.3"
tracing-subscriber.features = ["env-filter","json"]
redact.version = "0.1.10"
redact.features = ["serde"]

# config
config.version = "0.14"
config.features = ["toml"]

# serialize
postcard.version = "1.0"
postcard.features = ["alloc"]
serde.version = "1.0"
serde.features = ["derive"]
serde_with = "3.4.0"
serde_json = "1.0.111"

# errors
anyhow = "1"
thiserror = "2.0"

# grpc
tonic = "0.12"
tonic-reflection = "0.12"
tonic-health = "0.12"


# http
axum.version = "0.7"
tower.version = "0.5.0"
tower.features = ["steer", "make"]
hyper = "1.4"
tower-http = { version = "0.5", features = ["trace"] }

# sql
sea-orm.version = "1.0"
sea-orm.features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "debug-print" ]
atc-entity.path = "../../libs/atc/entity"
atc-migration.path = "../../libs/atc/migration"

# crypto
jsonwebtoken = "9"
ring = "0.17"

# http
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }

# queue
fred = { version = "9", features = ["i-pubsub", "partial-tracing", "subscriber-client"] }

# time
chrono = "0.4"

# stripe
async-stripe.version = "0.39"
async-stripe.features = ["runtime-tokio-hyper-rustls"]
