[package]
name = "atc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async
tokio.version = "1.34"
tokio.features = ["full"]
futures = "0.3.29"
flume = "0.11"
tokio-util.version = "0.7"
tokio-util.features = ["codec"]
tokio-stream.version = "0.1.14"
tokio-stream.features = ["sync"]

# types
paracosm-types.path = "../../libs/paracosm-types/rust"
atc-entity.path = "./entity"
uuid.version = "1.6.1"
uuid.features = ["fast-rng", "v7"]
enumflags2.version = "0.7.8"
enumflags2.features = ["serde"]
compact_str = "0.8.0-beta"

# logs
tracing = "0.1"
tracing-subscriber.version = "0.3"
tracing-subscriber.features = ["env-filter"]

# config
toml.version =  "0.7"
toml.features = ["parse"]

# serialize
postcard.version = "1.0"
postcard.features = ["alloc"]
serde.version = "1.0"
serde.features = ["derive"]

# errors
anyhow = "1"
thiserror = "1.0"

# grpc
tonic = "0.10"
tonic-reflection = "0.10.2"

# http
axum.version = "0.6.20"
axum.features = ["ws", "headers"]
tower.version = "0.4"
tower-http.version = "0.4.4"
tower-http.features = ["cors"]
hyper.version = "0.14.24"
hyper.features = ["stream"]

# sql
sea-orm.version = "0.12"
sea-orm.features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid" ]

# crypto
jsonwebtoken = "9"

# http
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# k8s
kube = { version = "0.87.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20.0", features = ["latest"] }

# queue
redis.version = "0.23"
redis.features = ["tokio-comp", "streams", "r2d2"]
