[package]
name = "atc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async
tokio.version = "1.34"
tokio.features = ["full"]
futures = "0.3.29"
flume = "0.11"
tokio-util.version = "0.7"
tokio-util.features = ["codec"]
tokio-stream.version = "0.1.14"
tokio-stream.features = ["sync"]

# types
elodin-types.path = "../../libs/elodin-types/rust"
uuid.version = "1.6.1"
uuid.features = ["fast-rng", "v7"]
enumflags2.version = "0.7.8"
enumflags2.features = ["serde"]

# logs
tracing = "0.1"
tracing-subscriber.version = "0.3"
tracing-subscriber.features = ["env-filter"]

# config
config.version = "0.14"
config.features = ["toml"]

# serialize
postcard.version = "1.0"
postcard.features = ["alloc"]
serde.version = "1.0"
serde.features = ["derive"]
serde_with = "3.4.0"
serde_json = "1.0.111"

# errors
anyhow = "1"
thiserror = "1.0"

# grpc
tonic = "0.11"
tonic-reflection = "0.11"
tonic-health = "0.11"


# http
axum.version = "0.6.20"
axum.features = ["ws", "headers"]
tower.version = "0.4"
hyper.version = "0.14.24"
hyper.features = ["stream"]
tower-http = "0.4.4"

# sql
sea-orm.version = "0.12"
sea-orm.features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "debug-print" ]
atc-entity.path = "../../libs/atc/entity"
atc-migration.path = "../../libs/atc/migration"

# crypto
jsonwebtoken = "9"

# http
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# k8s
kube = { version = "0.88", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.21", features = ["latest"] }

# queue
redis.version = "0.24"
redis.features = ["tokio-comp", "streams", "r2d2"]
redmq.path = "../../libs/redmq"

# time
chrono = "0.4"

# gcs
google-cloud-storage = { version = "0.15.0", default-features = false, features = ["auth", "rustls-tls", "trace"] }

const-fnv1a-hash = "1.1.0"
