database_url = "postgres://sphw:@localhost/atc_dev"
redis_url = "redis://localhost:6379"
migrate = true
env = "local"

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"
stripe_secret_key = "sk_test_51NUaAnG68UBhCjJFokYXChtW9vEOOBdVX1z8LZb3jQBn6PmVBh7Prg4gCxV9CDLvzhl53CLANPmHDREutxXxFXnj003lNQ0ef9"
stripe_webhook_secret = "whsec_6fb9fd43c282b06cecb7d0bf8ea6e7c453de50d48c371626b376c7e8283b0b9f"
base_url = "https://app.elodin.dev"

[api.stripe_plans.commercial]
monte_carlo_price = "price_1PtX1XG68UBhCjJFWfOr7ZBw"
subscription_price = "price_1PBnNtG68UBhCjJF82vJsv5n"
trial_length = 432000   # 5 days
monte_carlo_credit = 60000

[api.stripe_plans.non_commercial]
monte_carlo_price = "price_1PtX0TG68UBhCjJFYghysDOQ"
subscription_price = "price_1PBnNDG68UBhCjJFLZMvrR92"
trial_length = 2592000  # 30 days
monte_carlo_credit = 60

[garbage_collect]
enabled = true
timeout = 600.0

[monte_carlo]
sim_artifacts_bucket_name = ""
sim_results_bucket_name = ""
