database_url = "postgres://sphw@localhost/atc_dev"
redis_url = "redis://localhost:6379"
migrate = true

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"


[orca]
vm_namespace = "vms"
image_name = "elo-sim-runner:yhri5xjhdd1xvmrg1ffl19p3b81yrqq4"

[garbage_collect]
enabled = true
timeout = 600.0
