database_url = "postgres://sphw:@localhost/atc_dev"
redis_url = "redis://localhost:6379"
pod_name="elo-atc"
migrate = true

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"
stripe_secret_key = "sk_test_51NUaAnG68UBhCjJFokYXChtW9vEOOBdVX1z8LZb3jQBn6PmVBh7Prg4gCxV9CDLvzhl53CLANPmHDREutxXxFXnj003lNQ0ef9"
stripe_webhook_secret = "whsec_6fb9fd43c282b06cecb7d0bf8ea6e7c453de50d48c371626b376c7e8283b0b9f"
base_url = "https://app.elodin.dev"

[api.stripe_plans]
monte_carlo_price = "price_1PBnS5G68UBhCjJFgvwkvQwx"
commercial_price = "price_1PBnNtG68UBhCjJF82vJsv5n"
non_commercial_price = "price_1PBnNDG68UBhCjJFLZMvrR92"

[orca]
vm_namespace = "vms"
image_name = "elo-sim-agent:23jmxri34x9wjsq2xibc1wqzd1c8dfxi"

[garbage_collect]
enabled = true
timeout = 600.0

[monte_carlo]
sim_artifacts_bucket_name = ""
sim_results_bucket_name = ""
