database_url = "postgres://sphw@localhost/atc_dev"
redis_url = "redis://localhost:6379"
migrate = true

[api]
address = "[::]:50051"
auth0.domain = "dev-i2ytsp68gngieek3.us.auth0.com"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"

[orca]
vm_namespace = "vms"
image_name = "elo-sim-runner:ybpjb2wwjg1kmcl3m9mv5ayjjrn16j6x"

[garbage_collect]
enabled = true
timeout = 60.0
