database_url = "postgres://sphw@localhost/atc_dev"
redis_url = "redis://localhost:6379"

[api]
address = "[::]:50051"
auth0.domain = "dev-i2ytsp68gngieek3.us.auth0.com"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"

[orca]
vm_namespace = "vms"
image_name = "elo-web-runner:lz1kqw2ldlayx2fgsypsyls980cqpv0f"
