database_url = "postgres://postgres:secret@localhost/atc_dev"
redis_url = "redis://localhost:6379"
pod_name="elo-atc"
migrate = true
pod_name = "foo"

[api]
address = "[::]:50051"
auth0.domain = "auth.elodin.dev"
auth0.client_id = "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR"

[orca]
vm_namespace = "vms"
image_name = "elo-sim-agent:23jmxri34x9wjsq2xibc1wqzd1c8dfxi"

[garbage_collect]
enabled = true
timeout = 600.0

[monte_carlo]
sim_artifacts_bucket_name = ""
sim_results_bucket_name = ""
