[package]
name = "atc-entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# types
uuid = "1.6.1"
enumflags2.version = "0.7.8"
enumflags2.features = ["serde"]
paracosm-types.path = "../../../libs/paracosm-types/rust"

# serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"


# orm
sea-orm.version = "0.12"
sea-orm.features = ["with-uuid", "with-chrono"]

# chrono
chrono = "0.4"
