[package]
name = "elodin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
chrono = { version = "0.4.33", features = ["serde"] }
clap = { version = "4.4.18", features = ["derive"] }
elodin-types = { version = "0.1.0", path = "../../libs/elodin-types/rust" }
opener = "0.6.1"
reqwest = { version = "0.11.24", default-features = false, features = ["rustls-tls-webpki-roots", "json", "stream"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tar = "0.4.40"
tempfile = "3.10.0"
tokio = { version = "1.35.1", features = ["full"] }
tonic = { version = "0.11", features = ["tls", "tls-webpki-roots"] }
uuid = "1.7.0"
xdg = "2.5.2"
zstd = "0.13.0"

elodin-editor.path = "../../libs/elodin-editor"
elodin-editor.default-features = false
conduit.path = "../../libs/conduit"
conduit.features = ["tokio"]
bevy.version = "0.13"
flume = "0.11.0"
notify = "6.1.1"

tracing-subscriber = "0.3"
