[package]
name = "tegrastats-bridge"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
# async
stellarator.path = "../../libs/stellarator"
stellarator.features = ["miette"]
impeller-stellar.path = "../../libs/impeller/stellar"
futures-concurrency = "7.6"

# ser-de
impeller.path = "../../libs/impeller"
impeller.features = ["std"]
impeller-wkt.path = "../../libs/impeller/wkt"
impeller-wkt.features = ["gui", "std"]
zerocopy.version = "0.8.2"
db-macros.workspace = true

# errors
anyhow = "1"

# rand
fastrand = "2.2.0"

# os
sysinfo = "0.34"
