"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of schematic.kdl.
"""

# Schematic for the elodin.db showcase (examples/db-client/main.py).
# All components below are written by a plain-Python elodin.db process.
# Trajectory trail (last 3 of the 7 world_pos values are XYZ).

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.tabs(
            ui.hsplit(
                ui.viewport(
                    name="Chase",
                    fov=45.0,
                    active=True,
                    show_grid=True,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="drone.world_pos + (0,0,0,0, 0.4, 0.4, 0.25)",
                    look_at="drone.world_pos",
                    smoothing=0.0,
                    share=0.55,
                ),
                ui.vsplit(
                    ui.graph(
                        "drone.imu.accel",
                        name="Accelerometer (m/s^2)",
                    ),
                    ui.graph(
                        "drone.imu.gyro",
                        name="Gyroscope (rad/s)",
                    ),
                    ui.graph(
                        "drone.nav.speed",
                        name="Ground speed, stream-derived (m/s)",
                    ),
                    share=0.45,
                ),
                name="Flight",
            ),
            ui.vsplit(
                ui.graph(
                    "drone.battery.voltage",
                    name="Battery (V)",
                ),
                ui.graph(
                    "drone.motor.rpm",
                    name="Motor RPM",
                ),
                ui.graph(
                    "drone.status.armed",
                    name="Armed",
                ),
                ui.graph(
                    "drone.status.mode",
                    name="Flight mode (1=hover, 2=cruise)",
                ),
                name="Status",
            ),
            ui.vsplit(
                ui.graph(
                    "drone.world_pos",
                    name="World pos (quaternion + xyz)",
                ),
                ui.graph(
                    "drone.nav.speed",
                    name="Ground speed (m/s)",
                ),
                name="Pose",
            ),
        ),
        ui.object_3d(
            "drone.world_pos",
            mesh=ui.glb(
                "crazyflie.glb",
                scale=0.7,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="relative",
            animate=[
                ui.joint(
                    "Root.Propeller_0",
                    "(0, drone.propeller_angle[0], 0)",
                ),
                ui.joint(
                    "Root.Propeller_1",
                    "(0, drone.propeller_angle[1], 0)",
                ),
                ui.joint(
                    "Root.Propeller_2",
                    "(0, drone.propeller_angle[2], 0)",
                ),
                ui.joint(
                    "Root.Propeller_3",
                    "(0, drone.propeller_angle[3], 0)",
                ),
            ],
        ),
        ui.line_3d(
            "drone.world_pos",
            line_width=2.0,
            color="yalk",
            perspective=True,
        ),
        coordinate=ui.coordinate(
            frame="ENU",
        ),
        theme=ui.theme(
            mode="dark",
            scheme="default",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
