"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of .sensor-camera.rendered.kdl.
"""

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.hsplit(
            ui.viewport(
                name="Main",
                fov=45.0,
                active=False,
                show_grid=True,
                show_arrows=True,
                create_frustum=False,
                show_frustums=True,
                frustums_color="yellow",
                projection_color="white",
                frustums_thickness=0.006,
                show_view_cube=True,
                effects=True,
                hdr=False,
                cinematic=False,
                pos="(0,0,0,0, 14,14,10)",
                look_at="(0,0,0,0, 0,0,1)",
                smoothing=0.0,
            ),
            ui.vsplit(
                ui.sensor_view(
                    "cam_ball_a.scene_cam",
                    name="RGB Camera (Cyan Ball)",
                ),
                ui.sensor_view(
                    "cam_ball_b.thermal_cam",
                    name="Thermal (Magenta Ball)",
                ),
            ),
        ),
        ui.object_3d(
            "cam_ball_a.world_pos",
            mesh=ui.sphere(
                radius=0.3,
                color=ui.color(
                    0,
                    220,
                    220,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "cam_ball_b.world_pos",
            mesh=ui.sphere(
                radius=0.3,
                color=ui.color(
                    220,
                    0,
                    220,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "ball_1.world_pos",
            mesh=ui.sphere(
                radius=0.3,
                color=ui.color(
                    255,
                    140,
                    0,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "ball_2.world_pos",
            mesh=ui.sphere(
                radius=0.3,
                color=ui.color(
                    255,
                    255,
                    100,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "ball_3.world_pos",
            mesh=ui.sphere(
                radius=0.3,
                color=ui.color(
                    100,
                    255,
                    100,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "(0,0,0,1, 0,0,0)",
            mesh=ui.plane(
                width=12.0,
                depth=12.0,
                color=ui.color(
                    60,
                    120,
                    60,
                    255,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
        ),
        timeline=ui.timeline(
            played_color="yalk",
            future_color="white",
            follow_latest=True,
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
