apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- cluster-role.yaml
- service-account.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service.yaml

namespace: traefik
