"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of apollo-lander.kdl.
"""

# Apollo 11 descent SITL — ENU scene at Tranquility Base.
# Sky geometry from the NASA ALSJ ephemeris at landing
# (1969-07-20 20:17:39 UTC, 0.6875°N 23.4333°E):
#   Sun  az=88.81° el=10.65°   Earth az=272.16° el=59.43°
#   Earth–Moon distance 393,309 km (ALSJ / calendar-canada).
# KDL sun azimuth = compass azimuth + 180 (editor Bevy convention; see
# scene_environment.rs). Compass 88.81 → KDL 268.81. Low east sun for
# long westward shadows matching the target stills.
# Earth atmosphere at the real Earth center (ENU from site). Raymarched
# so the blue limb + sun disk render from lunar distance (~3.9e8 m).
# Single viewport: Bevy atmosphere supports one active atmosphere camera.
# Thruster exhaust: hanabi .effect files from pyrotechnique, driven by EQL.
# Absolute so children sit in body/ENU Z-up: the offsets below share the
# axes of the RcsTorque the sim indexes them with. Rx(+90°) lifts the Y-up
# GLB into that frame; translate stays in parent space, ahead of the rotate.
# Keep RCS_THRUSTERS in rcs_geometry.py in lockstep with these nozzles.
# Moon LRO mesh: under-site surface h = 1,724,837.623 m above center.
# Seat at -h so the surface is at ENU z = 0.
# Real Earth at ALSJ az/el / distance (scale=1 = true Earth radius).
# Rotate so the sun-lit hemisphere faces the site (approximate terminator).
# Constant screen-pixel trails (falcon9 fix: perspective=#false).

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.hsplit(
            ui.viewport(
                name="Tranquility Base",
                fov=45.0,
                near=1.0,
                active=True,
                show_grid=False,
                show_arrows=True,
                create_frustum=False,
                show_frustums=False,
                frustums_color="yellow",
                projection_color="white",
                frustums_thickness=0.006,
                show_view_cube=True,
                effects=True,
                hdr=True,
                cinematic=False,
                bloom=ui.bloom(
                    preset="old_school",
                    intensity=0.22,
                    threshold=0.78,
                    threshold_softness=0.12,
                ),
                ev100=13.2,
                pos="lander.world_pos.translate_world(10.0, 10.0, 4.0)",
                look_at="lander.world_pos",
                smoothing=0.0,
            ),
            ui.vsplit(
                ui.hsplit(
                    ui.graph(
                        "lander.altitude[0], lander_truth.altitude[0], lander_truth.slant_range[0]",
                        name="Altitude vs real + radar slant (m)",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                            ui.color(
                                196,
                                160,
                                70,
                                255,
                            ),
                        ],
                    ),
                    ui.graph(
                        "lander_truth.vertical_speed[0], lander.vertical_speed[0]",
                        name="Descent rate (m/s)",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                        ],
                    ),
                ),
                ui.hsplit(
                    ui.graph(
                        "lander.horizontal_speed[0], lander_truth.horizontal_speed[0]",
                        name="Horizontal speed vs reconstructed (m/s)",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                        ],
                    ),
                    ui.graph(
                        "lander.pitch[0], lander_truth.pitch[0]",
                        name="Pitch vs gimbal-derived truth (deg)",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                        ],
                    ),
                ),
                ui.hsplit(
                    ui.graph(
                        "lander.throttle_cmd[0], lander.throttle[0]",
                        name="DPS throttle",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                        ],
                    ),
                    ui.graph(
                        "lander.propellant[0], lander.rcs_propellant[0]",
                        name="Propellant remaining (kg)",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                        ],
                    ),
                ),
                ui.hsplit(
                    ui.graph(
                        "lander.main_thrust_viz[2]",
                        name="Engine thrust (fraction of max)",
                        colors=[
                            "orange",
                        ],
                    ),
                    ui.graph(
                        "lander.rcs_torque",
                        name="RCS torque command (roll/pitch/yaw, N·m)",
                        colors=[
                            ui.color(
                                106,
                                155,
                                165,
                                255,
                            ),
                            ui.color(
                                196,
                                160,
                                70,
                                255,
                            ),
                            ui.color(
                                114,
                                87,
                                179,
                                255,
                            ),
                        ],
                    ),
                ),
                share=0.536157,
            ),
        ),
        ui.object_3d(
            "lander.world_pos",
            mesh=ui.glb(
                "apollo-lunar-module.glb",
                scale=1.0,
                translate=(0.0, 0.0, -2.5),
                rotate=(90.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="ENU",
            orientation="absolute",
            thrusters=[
                ui.thruster(
                    name="DPS",
                    body_frame=True,
                    position=(0.0, 0.0, -1.9),
                    direction=(0.0, 0.0, -1.0),
                    intensity="lander.main_thrust_viz[2]",
                    effect="effects/apollo-lander/descent_plume.effect",
                    cutoff=0.02,
                    scale=1.0,
                    light=ui.thruster_light(
                        color=(1.0, 0.95, 0.88),
                        intensity=3000000.0,
                        range=40.0,
                        offset=0.8,
                        shadows=True,
                    ),
                    extra_effects=[
                        "effects/apollo-lander/descent_glow.effect",
                    ],
                ),
                ui.thruster(
                    name="rcs_0",
                    body_frame=True,
                    position=(1.089, 1.506, 0.87),
                    direction=(0.0, 1.0, 0.0),
                    intensity="lander.rcs_thruster_viz[0]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_1",
                    body_frame=True,
                    position=(1.388, 1.361, 0.874),
                    direction=(1.0, 0.0, 0.0),
                    intensity="lander.rcs_thruster_viz[1]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_2",
                    body_frame=True,
                    position=(-1.18, 1.369, 0.527),
                    direction=(0.0, 0.0, -1.0),
                    intensity="lander.rcs_thruster_viz[2]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_3",
                    body_frame=True,
                    position=(-1.36, 1.361, 0.855),
                    direction=(-1.0, 0.0, 0.0),
                    intensity="lander.rcs_thruster_viz[3]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_4",
                    body_frame=True,
                    position=(-1.062, 1.507, 0.858),
                    direction=(0.0, 1.0, 0.0),
                    intensity="lander.rcs_thruster_viz[4]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_5",
                    body_frame=True,
                    position=(-1.249, -1.23, 1.127),
                    direction=(0.0, 0.0, 1.0),
                    intensity="lander.rcs_thruster_viz[5]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_6",
                    body_frame=True,
                    position=(-1.429, -1.28, 0.916),
                    direction=(-1.0, 0.0, 0.0),
                    intensity="lander.rcs_thruster_viz[6]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_7",
                    body_frame=True,
                    position=(-1.232, -1.428, 0.912),
                    direction=(0.0, -1.0, 0.0),
                    intensity="lander.rcs_thruster_viz[7]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_8",
                    body_frame=True,
                    position=(1.297, -1.243, 1.127),
                    direction=(0.0, 0.0, 1.0),
                    intensity="lander.rcs_thruster_viz[8]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_9",
                    body_frame=True,
                    position=(1.296, -1.243, 0.694),
                    direction=(0.0, 0.0, -1.0),
                    intensity="lander.rcs_thruster_viz[9]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_10",
                    body_frame=True,
                    position=(1.484, -1.26, 0.905),
                    direction=(1.0, 0.0, 0.0),
                    intensity="lander.rcs_thruster_viz[10]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_11",
                    body_frame=True,
                    position=(1.314, -1.442, 0.908),
                    direction=(0.0, -1.0, 0.0),
                    intensity="lander.rcs_thruster_viz[11]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_12",
                    body_frame=True,
                    position=(1.207, 1.369, 1.201),
                    direction=(0.0, 0.0, 1.0),
                    intensity="lander.rcs_thruster_viz[12]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_13",
                    body_frame=True,
                    position=(1.207, 1.369, 0.527),
                    direction=(0.0, 0.0, -1.0),
                    intensity="lander.rcs_thruster_viz[13]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_14",
                    body_frame=True,
                    position=(-1.249, -1.23, 0.694),
                    direction=(0.0, 0.0, -1.0),
                    intensity="lander.rcs_thruster_viz[14]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_15",
                    body_frame=True,
                    position=(-1.18, 1.369, 1.2),
                    direction=(0.0, 0.0, 1.0),
                    intensity="lander.rcs_thruster_viz[15]",
                    effect="effects/apollo-lander/rcs_puff.effect",
                    cutoff=0.006,
                    scale=1.0,
                ),
            ],
        ),
        ui.object_3d(
            "(0,0,0,1, 0,0,0)",
            mesh=ui.sphere(
                radius=0.02,
                color="white",
                emissivity=0.0,
            ),
            frame="ENU",
            orientation="relative",
            thrusters=[
                ui.thruster(
                    name="ground_dust",
                    body_frame=True,
                    position=(0.0, 0.0, 0.0),
                    direction=(0.0, -1.0, 0.0),
                    intensity="lander.dust_viz[0]",
                    effect="effects/apollo-lander/ground_dust.effect",
                    emission_rate=2800.0,
                    cutoff=0.005,
                    scale=1.0,
                ),
            ],
        ),
        ui.object_3d(
            "(0,0,0,1, 0,0,-1724837.623)",
            mesh=ui.glb(
                "moon.glb",
                scale=1798000.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(25.32, 21.2, 79.59),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="ENU",
            orientation="relative",
        ),
        ui.object_3d(
            "(0,0,0,1, -199014543, 7506228, 337157270)",
            mesh=ui.glb(
                "earth.glb",
                scale=1.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 90.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            frame="ENU",
            orientation="relative",
        ),
        ui.line_3d(
            "lander.world_pos",
            line_width=2.0,
            color=ui.color(
                70,
                130,
                240,
                200,
            ),
            perspective=False,
            frame="ENU",
        ),
        ui.line_3d(
            "lander_truth.world_pos",
            line_width=2.0,
            color=ui.color(
                60,
                200,
                90,
                200,
            ),
            perspective=False,
            frame="ENU",
        ),
        coordinate=ui.coordinate(
            frame="ENU",
        ),
        theme=ui.theme(
            mode="dark",
            scheme="default",
        ),
        timeline=ui.timeline(
            played_color="yalk",
            future_color="white",
            follow_latest=False,
            range="last_30s",
        ),
        environment=ui.environment(
            sun=ui.sun(
                azimuth=268.81,
                elevation=10.65,
                illuminance=130000.0,
                shadows=True,
            ),
            ambient=0.02,
            sky="black",
            atmosphere=ui.atmosphere(
                origin=(-199014543.0, 7506228.0, 337157270.0),
                inner_radius=6378140.0,
                outer_radius=6478140.0,
                ground_albedo=(0.2, 0.22, 0.18),
                raymarched=True,
            ),
        ),
        telemetry_mode=True,
    )


if __name__ == "__main__":
    print(build().emit_kdl())
