syntax = "proto3";

package elodin.db.v1;

import "elodin/db/v1/common.proto";

service QueryService {
  rpc GetTimeRange(GetTimeRangeRequest) returns (GetTimeRangeResponse);
  rpc DumpMetadata(DumpMetadataRequest) returns (DumpMetadataResponse);
  rpc DumpSchema(DumpSchemaRequest) returns (DumpSchemaResponse);
  rpc GetTimeSeries(GetTimeSeriesRequest) returns (stream GetTimeSeriesResponse);
  rpc Sql(SqlRequest) returns (stream SqlResponse);
}

message GetTimeRangeRequest {}

message GetTimeRangeResponse {
  bool has_data = 1;
  sfixed64 earliest_ns = 2;
  sfixed64 last_updated_ns = 3;
}

message DumpMetadataRequest {}

message DumpMetadataResponse {
  repeated ComponentMetadata components = 1;
  repeated MessageMetadata messages = 2;
  DbConfig config = 3;
}

message DumpSchemaRequest {}

message DumpSchemaResponse {
  repeated ComponentSchemaSnapshot components = 1;
}

message GetTimeSeriesRequest {
  string component = 1;
  sfixed64 start_ns = 2;
  sfixed64 end_ns = 3; // 0 = open-ended
  uint64 limit = 4; // 0 = unlimited
  uint32 max_points = 5; // 0 = raw
  uint32 element_index = 6;
}

message TimeSeriesHeader {
  string component = 1;
  PrimType prim_type = 2;
  repeated uint64 dims = 3;
  repeated string element_names = 4;
}

message TimeSeriesData {
  repeated sfixed64 timestamps_ns = 1;
  bytes packed_values = 2;
}

message GetTimeSeriesResponse {
  oneof chunk {
    TimeSeriesHeader header = 1;
    TimeSeriesData data = 2;
  }
}

message SqlRequest {
  string sql = 1;
}

message SqlResponse {
  bytes ipc = 1;
}
