"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of bdx.kdl.
"""

# BDX RC jet ECEF scene over the Mojave RC field.
#
# Site (baked): pilot pad 35.350664 N, 117.809027 W, ellipsoid height
# 589.274 m — also the mojave_rc_field region center, so ENU east/north
# are zero. Physics uses that ellipsoid height; world_mesh +Z (below)
# lifts the planar DEM onto that pad. Chase / TGT / top-down
# ECEF offsets keep the same local-ENU geometry as the Death Valley
# scene at heading 350°.
#
# Cinematic Earth lives on `world.sensor_camera(..., cinematic=True)`
# (render-server FPV), not on these viewports. The Boson-style LWIR camera
# uses this terrain through a normal off-screen view plus its final sensor pass.
# Planar TerrainModel: y=0 at region min (450 m), then Y -= 0.4*(max-min)
# = 700 m. Pad DEM ≈ 621.5 m orthometric, so
# tz = 700 - (621.5 - 450) ≈ 528 puts the mesh on the ENU origin
# (physics ellipsoid 589.274 m). Align surfaces; do not add the ~32 m geoid.
# ECEF pose: the gauge derives the local vertical from the
# vehicle's own position (ellipsoid normal).
# Package render mesh: already Elodin body (X forward, Y left, Z up, CG
# origin). Absolute ECEF identity would map those axes onto ECEF, so do
# not add a glTF Y-up lift — assets/bdx.glb is hash-checked by the tests.

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.world_mesh(
            "mojave_rc_field",
            translate=(0.0, 0.0, 528.0),
            frame="ENU",
            visible=True,
        ),
        ui.tabs(
            ui.hsplit(
                ui.vsplit(
                    ui.horizon_gauge(
                        "bdx.world_pos",
                        name="ADI",
                        share=3.0,
                    ),
                    ui.graph(
                        "bdx.alpha",
                        name="Angle of Attack (rad)",
                    ),
                    ui.graph(
                        "bdx.aero_valid",
                        name="Aero Validity Flag",
                    ),
                    share=0.4,
                ),
                ui.viewport(
                    name="Chase",
                    fov=45.0,
                    near=1.0,
                    active=True,
                    show_grid=False,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="bdx.world_pos.translate_world(-3.128, -11.885, -10.827)",
                    look_at="bdx.world_pos.translate_world(-0.087, 2.067, 5.976)",
                    up="(-0.381, -0.721, 0.578)",
                    smoothing=0.0,
                ),
                ui.vsplit(
                    ui.viewport(
                        name="TGTViewport",
                        fov=45.0,
                        active=False,
                        show_grid=False,
                        show_arrows=True,
                        create_frustum=False,
                        show_frustums=False,
                        frustums_color="yellow",
                        projection_color="white",
                        frustums_thickness=0.006,
                        show_view_cube=True,
                        effects=True,
                        hdr=False,
                        cinematic=False,
                        pos="target.world_pos.translate_world(1.078, -0.099, 0.931)",
                        look_at="bdx.world_pos",
                        smoothing=0.0,
                    ),
                    ui.viewport(
                        name="FPVViewport",
                        fov=45.0,
                        active=False,
                        show_grid=False,
                        show_arrows=True,
                        create_frustum=False,
                        show_frustums=False,
                        frustums_color="yellow",
                        projection_color="white",
                        frustums_thickness=0.006,
                        show_view_cube=True,
                        effects=True,
                        hdr=False,
                        cinematic=False,
                        pos="bdx.world_pos.translate(1,0,0.1)",
                        look_at="bdx.world_pos.translate(2,0,0.1)",
                        up="bdx.world_pos.direction(0,0,1)",
                        smoothing=0.0,
                    ),
                    ui.sensor_view(
                        "bdx.fpv_cam",
                        name="FPV (sensor_camera)",
                    ),
                    ui.sensor_view(
                        "bdx.ir_cam",
                        name="LWIR (Boson+ 640)",
                    ),
                    share=0.4,
                ),
                name="Main View",
            ),
            ui.vsplit(
                ui.hsplit(
                    ui.graph(
                        "bdx.velocity_body",
                        name="Body Velocity (m/s)",
                    ),
                    ui.graph(
                        "bdx.geodetic.alt_m",
                        name="Geodetic Altitude (m)",
                    ),
                ),
                ui.hsplit(
                    ui.graph(
                        "bdx.control_surfaces",
                        name="Control Surfaces (rad)",
                    ),
                    ui.graph(
                        "bdx.dynamic_pressure, bdx.mach",
                        name="Dynamic Pressure / Mach",
                    ),
                ),
                name="Flight Data",
            ),
            ui.vsplit(
                ui.hsplit(
                    ui.graph(
                        "bdx.thrust",
                        name="Thrust (N)",
                    ),
                    ui.graph(
                        "bdx.spool_speed",
                        name="Effective Throttle (spool)",
                    ),
                ),
                ui.hsplit(
                    ui.graph(
                        "bdx.fuel_mass",
                        name="Fuel Mass (kg)",
                    ),
                    ui.graph(
                        "bdx.fuel_flow",
                        name="Fuel Flow (kg/s)",
                    ),
                ),
                name="Propulsion",
            ),
            ui.vsplit(
                ui.graph(
                    "bdx.control_commands",
                    name="Control Commands (rad/normalized)",
                ),
                ui.graph(
                    "bdx.control_surfaces",
                    name="Control Surfaces (rad)",
                ),
                name="Control Input",
            ),
            ui.vsplit(
                ui.hsplit(
                    ui.graph(
                        "bdx.alpha",
                        name="Angle of Attack (rad)",
                    ),
                    ui.graph(
                        "bdx.beta",
                        name="Sideslip (rad)",
                    ),
                ),
                ui.hsplit(
                    ui.graph(
                        "bdx.aero_coefs.CL, bdx.aero_coefs.CD",
                        name="CL, CD",
                    ),
                    ui.graph(
                        "bdx.aero_coefs.Cm",
                        name="Pitch Moment Cm",
                    ),
                ),
                name="Aerodynamics",
            ),
            ui.hsplit(
                ui.viewport(
                    name="Top-Down View",
                    fov=60.0,
                    active=False,
                    show_grid=False,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=False,
                    pos="bdx.world_pos.translate_world(-57.076, -108.214, 86.787)",
                    look_at="bdx.world_pos",
                    up="(0.270, 0.512, 0.816)",
                    smoothing=0.0,
                ),
                ui.query_plot(
                    "Ground Track (ENU)",
                    "SELECT bdx_pos_enu.bdx_pos_enu[1], bdx_pos_enu.bdx_pos_enu[2] FROM bdx_pos_enu",
                    refresh_interval_ms=500.0,
                    auto_refresh=True,
                    color="cyan",
                    query_type="sql",
                    plot_mode="xy",
                    x_label="East (m)",
                    y_label="North (m)",
                ),
                name="Navigation",
            ),
        ),
        ui.object_3d(
            "bdx.world_pos",
            mesh=ui.glb(
                "bdx.glb",
                scale=1.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="absolute",
            icon=ui.icon(
                builtin="flight_takeoff",
                color=ui.color(
                    76,
                    175,
                    80,
                    255,
                ),
                size=32.0,
                visibility=ui.visibility_range(
                    min=50.0,
                    max=3.4028235e38,
                    fade_distance=50.0,
                ),
            ),
        ),
        ui.object_3d(
            "target.world_pos",
            mesh=ui.glb(
                "edu-450-v2-drone.glb",
                scale=10.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(90.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="absolute",
            icon=ui.icon(
                builtin="adjust",
                color=ui.color(
                    244,
                    67,
                    54,
                    255,
                ),
                size=32.0,
                visibility=ui.visibility_range(
                    min=50.0,
                    max=3.4028235e38,
                    fade_distance=50.0,
                ),
            ),
        ),
        ui.vector_arrow(
            "(1, 0, 0)",
            origin="bdx.world_pos",
            name="Forward (X)",
            color=ui.color(
                255,
                0,
                0,
                150,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(0, 1, 0)",
            origin="bdx.world_pos",
            name="Left (Y)",
            color=ui.color(
                0,
                255,
                0,
                150,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.vector_arrow(
            "(0, 0, 1)",
            origin="bdx.world_pos",
            name="Up (Z)",
            color=ui.color(
                0,
                0,
                255,
                150,
            ),
            scale=1.0,
            body_frame=True,
            normalize=False,
            show_name=True,
            thickness=0.1,
            label_position=None,
        ),
        ui.line_3d(
            "bdx.world_pos",
            line_width=3.0,
            color="yolk",
            perspective=False,
        ),
        coordinate=ui.coordinate(
            frame="ECEF",
            lat=35.350664,
            lon=-117.809027,
            alt=589.274,
        ),
        timeline=ui.timeline(
            played_color="yalk",
            future_color="white",
            follow_latest=True,
            range="last_30s",
        ),
        telemetry_mode=True,
    )


if __name__ == "__main__":
    print(build().emit_kdl())
