"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of visual_check.kdl.
"""

# Same planar DEM lift as bdx.kdl: tz = 700 - (621.5 - 450) puts the mesh
# surface on the pad's ENU origin (physics ellipsoid 589.274 m).
# Same contract as bdx.kdl: absolute ECEF body axes + Rx(+90°) so the
# Y-up drone GLB sits upright in the LWIR chip (Relative would similarity-
# rotate it by the site's ECEF level attitude).

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.world_mesh(
            "mojave_rc_field",
            translate=(0.0, 0.0, 528.0),
            frame="ENU",
            visible=True,
        ),
        ui.tabs(
            ui.hsplit(
                ui.sensor_view(
                    "cam.ir_rgba",
                    name="LWIR RGBA",
                ),
                ui.sensor_view(
                    "cam.ir_gray8",
                    name="LWIR gray8",
                ),
                name="LWIR parity",
            ),
        ),
        ui.object_3d(
            "target.world_pos",
            mesh=ui.glb(
                "edu-450-v2-drone.glb",
                scale=10.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(90.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="absolute",
        ),
        coordinate=ui.coordinate(
            frame="ECEF",
            lat=35.350664,
            lon=-117.809027,
            alt=589.274,
        ),
        timeline=ui.timeline(
            played_color="yalk",
            future_color="white",
            follow_latest=True,
            range="last_5s",
        ),
        environment=ui.environment(
            sun=ui.sun(
                illuminance=100000.0,
                shadows=True,
                direction=(-0.87, -0.488, -0.07),
            ),
            ambient=0.05,
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
