"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of covariance-ellipsoids.kdl.
"""

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.hsplit(
            ui.viewport(
                name="Cholesky: P = LL^T",
                fov=45.0,
                active=True,
                show_grid=True,
                show_arrows=True,
                create_frustum=False,
                show_frustums=False,
                frustums_color="yellow",
                projection_color="white",
                frustums_thickness=0.006,
                show_view_cube=True,
                effects=True,
                hdr=False,
                cinematic=False,
                pos="(0,0,0,1, 0,-6,4)",
                look_at="cholesky.world_pos",
                smoothing=0.0,
            ),
            ui.viewport(
                name="Direct covariance: P",
                fov=45.0,
                active=True,
                show_grid=True,
                show_arrows=True,
                create_frustum=False,
                show_frustums=False,
                frustums_color="yellow",
                projection_color="white",
                frustums_thickness=0.006,
                show_view_cube=True,
                effects=True,
                hdr=False,
                cinematic=False,
                pos="(0,0,0,1, 8,-6,4)",
                look_at="covariance.world_pos",
                smoothing=0.0,
                frame="ENU",
            ),
        ),
        ui.object_3d(
            "cholesky.world_pos",
            mesh=ui.ellipsoid(
                scale="(1, 1, 1)",
                color=ui.color(
                    255,
                    152,
                    0,
                    72,
                ),
                error_covariance_cholesky="cholesky.cholesky_factor",
                error_confidence_interval=70.0,
                show_grid=True,
                grid_color=ui.color(
                    255,
                    193,
                    7,
                    220,
                ),
            ),
            orientation="relative",
        ),
        ui.object_3d(
            "covariance.world_pos",
            mesh=ui.ellipsoid(
                scale="(1, 1, 1)",
                color=ui.color(
                    3,
                    169,
                    244,
                    72,
                ),
                error_covariance="covariance.error_covariance",
                error_confidence_interval=70.0,
                show_grid=True,
                grid_color=ui.color(
                    0,
                    188,
                    212,
                    220,
                ),
            ),
            frame="ENU",
            orientation="relative",
        ),
        coordinate=ui.coordinate(
            frame="ENU",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
