apiVersion: apps/v1
kind: Deployment
metadata:
  name: elo-atc
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: elo-atc
      containers:
      - name: elo-atc
        imagePullPolicy: Always
        image: elodin-infra/elo-atc:latest
        env:
        - name: ELODIN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUST_LOG
          value: info,atc=debug,redmq=debug
        volumeMounts:
        - name: config
          mountPath: /etc/elodin
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50051
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50051
        resources:
          requests:
            cpu: 200m
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: elo-atc-config
