apiVersion: apps/v1
kind: Deployment
metadata:
  name: elo-atc
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: elo-atc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: DoesNotExist
      containers:
      - name: elo-atc
        imagePullPolicy: Always
        image: elodin-infra/elo-atc:latest
        envFrom:
        - configMapRef:
            name: elo-atc-config
        - secretRef:
            name: elo-atc-secret
        env:
        - name: ELODIN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ELODIN_ORCA.IMAGE_NAME
          value: elodin-infra/elo-sim-agent:latest
        - name: RUST_LOG
          value: info,atc=debug,redmq=debug
        volumeMounts:
        - name: config
          mountPath: /etc/elodin
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50051
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50051
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: elo-atc-config
