apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: elo-atc
    includeSelectors: true

resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
