apiVersion: apps/v1
kind: Deployment
metadata:
  name: elo-atc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      atc-role: proxy
  template:
    metadata:
      labels:
        atc-role: proxy
    spec:
      serviceAccountName: elo-atc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - default
      containers:
      - name: elo-atc-proxy
        imagePullPolicy: Always
        image: elodin-infra/elo-atc:latest
        env:
        - name: ELODIN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUST_LOG
          value: info,atc=debug,redmq=debug
        volumeMounts:
        - name: config
          mountPath: /etc/elodin
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50051
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50051
        resources:
          requests:
            cpu: 200m
      volumes:
      - name: config
        configMap:
          name: elo-atc-proxy-config
