"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of schematic_ned.kdl.
"""

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.hsplit(
            ui.tabs(
                ui.viewport(
                    name="Viewport",
                    active=True,
                    show_grid=True,
                    hdr=True,
                    pos="(0,0,0,0, 8,2,-4)",
                    look_at="(0,0,0,0, 0,0,-3)",
                    frame="NED",
                ),
                ui.inspector(),
            ),
        ),
        ui.object_3d(
            "ball.world_pos",
            mesh=ui.sphere(
                radius=0.2,
                color="orange",
            ),
            frame="NED",
        ),
        ui.line_3d(
            "ball.world_pos",
            line_width=2.0,
            color="white",
            frame="NED",
        ),
        ui.vector_arrow(
            "ball.world_vel[3],ball.world_vel[4],ball.world_vel[5]",
            origin="ball.world_pos",
            name="Ball Velocity",
            color=ui.color(
                255,
                230,
                51,
                100,
            ),
            label_position="0.3m",
            frame="NED",
        ),
        ui.object_3d(
            "(0,0,0,1, 0,0,0)",
            mesh=ui.plane(
                width=2000.0,
                depth=2000.0,
                color=ui.color(
                    32,
                    128,
                    32,
                    125,
                ),
            ),
            frame="NED",
        ),
        coordinate=ui.coordinate(
            frame="NED",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
