"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of terrain.kdl.
"""

import elodin.ui as ui


def build() -> ui.Schematic:
    return ui.schematic(
        ui.world_mesh(
            "brienz",
            visible=True,
        ),
        ui.viewport(
            name="Brienz Terrain",
            fov=60.0,
            near=1.0,
            active=True,
            show_grid=False,
            show_arrows=True,
            create_frustum=False,
            show_frustums=False,
            frustums_color="yellow",
            projection_color="white",
            frustums_thickness=0.006,
            show_view_cube=True,
            effects=True,
            hdr=True,
            cinematic=False,
            pos="(0,0,0,1, 4560,-4560,2640)",
            look_at="(0,0,0,1, 0,0,-120)",
            up="(0,0,1)",
            smoothing=0.0,
            frame="ENU",
        ),
        coordinate=ui.coordinate(
            frame="ENU",
        ),
    )


if __name__ == "__main__":
    print(build().emit_kdl())
