apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- cluster-roles.yaml
- network-policy.yaml
- placeholder-priority.yaml
- sim-runner-balloon.yaml

namespace: elodin-vms
