apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.239.39.199
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
