import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :paracosm_dashboard, ParacosmDashboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: ParacosmDashboard.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :paracosm_dashboard, ParacosmDashboardWeb.UserAuth,
  client_id: "sC8TxakUl2GPeVHyYwbOGj6cuzSIxKYR",
  client_secret: "Rx5d-nJWafMuEcmSRXiUtlCjArTBtPMsjU588CDjq3RjFe1fTSVng2dWmjnyWHBw",
  redirect_uri: "http://localhost:4000/oauth/callback",
  site: "https://dev-i2ytsp68gngieek3.us.auth0.com",
  authorize_url: "/authorize",
  token_url: "/oauth/token",
  user_url: "/userinfo",
  authorization_params: [scope: "openid profile email"],
  auth_method: :client_secret_post
