[package]
name = "sim-agent"
version = "0.1.0"
edition = "2021"
metadata.dist.dist = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# grpc
tonic = { version = "0.12", features = ["zstd"] }
tonic-reflection = "0.12"
tonic-health = "0.12"
http-serde = "2.1"

# codec
tokio-util.version = "0.7"
tokio-util.features = ["codec"]

# async
tokio.version = "1.34"
tokio.features = ["full"]
hyper-util.version = "0.1.6"
hyper-util.features = ["tokio"]
flume = "0.11"
futures = "0.3.29"
stellarator.path = "../../libs/stellarator"

# logs
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# errors
anyhow = "1"

# types
serde.version = "1.0"
serde.features = ["derive"]
serde_json = "1.0.115"
serde_with = "3.7.0"
postcard.version = "1.0.8"
postcard.features = ["alloc"]
elodin-types.path = "../../libs/elodin-types/rust"

# bytes
bytes = "1.5"

# config
config.version = "0.14"
config.features = ["toml"]

# message queue
fred = { version = "9", features = ["partial-tracing" ] }
redmq.version = "0.1.0"
redmq.path = "../../libs/redmq"

#time
chrono = "0.4.33"

google-cloud-storage = { version = "0.20.0", default-features = false, features = ["auth", "rustls-tls", "trace"] }
tar = "0.4.40"
zstd = "0.13.0"
tempfile = "3.10.0"
nox-ecs = { path = "../../libs/nox-ecs" }
impeller-db = { path = "../../libs/impeller2/db" }
atc-entity = { path = "../../libs/atc/entity" }
tower = { version = "0.5.0", features = ["util"] }
crc = "3.0.1"
gethostname = "0.4.3"
thiserror = "2.0"
tokio-stream = "0.1.14"

sea-orm.version = "1.0"
sea-orm.features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "debug-print" ]

# azure
azure_core.version = "0.21.0"
azure_core.features = ["tokio", "tokio-fs", "enable_reqwest_rustls"]
azure_identity.version = "0.21.0"
azure_identity.features = ["enable_reqwest_rustls"]
azure_storage_blobs.version = "0.21.0"
azure_storage_blobs.features = ["enable_reqwest_rustls"]
azure_storage.version = "0.21.0"
azure_storage.features = ["enable_reqwest_rustls"]


[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = { git = "https://github.com/rust-vsock/tokio-vsock", rev = "3a41323", features = ["tonic-conn"] }
