[package]
name = "sim-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# grpc
tonic = "0.10"
tonic-reflection = "0.10.2"

# codec
tokio-util.version = "0.7"
tokio-util.features = ["codec"]

# async
tokio.version = "1.34"
tokio.features = ["full"]
flume = "0.11"

# logs
tracing = "0.1"
tracing-subscriber = "0.3"

# errors
anyhow = "1"

# elodin
elodin-core.path = "../../libs/elodin-core"
bevy.version = "0.12"
elodin-conduit.path = "../../libs/elodin-conduit"
elodin-conduit.features = ["tokio"]

# types
serde.version = "1.0"
serde.features = ["derive"]
postcard.version = "1.0.8"
postcard.features = ["alloc"]
elodin-types.path = "../../libs/elodin-types/rust"


# python
pyo3.version = "0.20.0"
elodin-py.path = "../../libs/elodin-py"

# bytes
bytes = "1.5"

# config
config.version = "0.13.1"
config.features = ["toml"]

# message queue
redis.version = "0.23"
redis.features = ["tokio-comp", "streams"]
redmq.version = "0.1.0"
redmq.path = "../../libs/redmq"

#time
chrono = "0.4.33"
