[package]
name = "sim-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# grpc
tonic = "0.11"
tonic-reflection = "0.11"
tonic-health = "0.11"

# codec
tokio-util.version = "0.7"
tokio-util.features = ["codec"]

# async
tokio.version = "1.34"
tokio.features = ["full"]
flume = "0.11"

# logs
tracing = "0.1"
tracing-subscriber = "0.3"

# errors
anyhow = "1"

# elodin
conduit.path = "../../libs/conduit"
conduit.default-features = false
conduit.features = ["tokio"]

# types
serde.version = "1.0"
serde.features = ["derive"]
postcard.version = "1.0.8"
postcard.features = ["alloc"]
elodin-types.path = "../../libs/elodin-types/rust"

# bytes
bytes = "1.5"

# config
config.version = "0.14"
config.features = ["toml"]

# message queue
redis.version = "0.24"
redis.features = ["tokio-comp", "streams"]
redmq.version = "0.1.0"
redmq.path = "../../libs/redmq"

#time
chrono = "0.4.33"

google-cloud-storage = { version = "0.15.0", default-features = false, features = ["auth", "rustls-tls", "trace"] }
tar = "0.4.40"
zstd = "0.13.0"
tempfile = "3.10.0"
nox = { path = "../../libs/nox" }
nox-ecs = { path = "../../libs/nox-ecs" }
