"""Generated by `elodin schematic to-python`.

Typed elodin.ui translation of falcon9.kdl.
"""

# Falcon 9 launch-to-landing cinematic ECEF scene.
# Keep live graph redraw bounded at 1000 Hz.
# The CRS-12 playhead drives the built-in Earth's ephemeris sun.
# Cinematic chase viewport with telemetry panels.
# Same series as the GLB (visual_pos); body +X ~20 m is near CoM so framing matches the old world_pos chase.
# Rotate the 70 m Y-up GLB onto the simulation's body +X axis.
# Spawn the Merlin plume at the bell-exit plane.
# Keep the exhaust trail world-anchored while thinning it with air density.
# Cold-gas RCS: falcon9-sized darts (rcs_dart) at interstage station 46 m.
# World-fixed launch-pad smoke.
# Landing dust and ASDS visual at LZ-1.
# Barge floats above the coarse globe until the surface fix.
# CRS-12 truth ghost.

import elodin.ui as ui

def build() -> ui.Schematic:
    return ui.schematic(
        ui.vsplit(
            ui.hsplit(
                ui.viewport(
                    name="Chase",
                    fov=45.0,
                    near=1.0,
                    active=True,
                    show_grid=False,
                    show_arrows=True,
                    create_frustum=False,
                    show_frustums=False,
                    frustums_color="yellow",
                    projection_color="white",
                    frustums_thickness=0.006,
                    show_view_cube=True,
                    effects=True,
                    hdr=False,
                    cinematic=True,
                    pos="booster.visual_pos.translate(20, 0, 0).translate_world(46.740, -100.549, -144.705)",
                    look_at="booster.visual_pos.translate(20, 0, 0).translate_world(1.433, -8.661, 4.788)",
                    up="(0.1433, -0.8661, 0.4788)",
                    smoothing=0.0,
                    share=0.72,
                ),
                ui.vsplit(
                    ui.hsplit(
                        ui.graph(
                            "booster.ground_speed[0], booster_truth.ground_speed[0]",
                            name="Speed vs recorded (m/s)",
                            colors=[
                                "blue",
                                "green",
                            ],
                        ),
                        ui.graph(
                            "booster.mach[0]",
                            name="Mach",
                            colors=[
                                "white",
                            ],
                        ),
                    ),
                    ui.hsplit(
                        ui.graph(
                            "booster.altitude_geodetic[0], booster_truth.altitude_geodetic[0]",
                            name="Altitude vs recorded (m)",
                            colors=[
                                "blue",
                                "green",
                            ],
                        ),
                        ui.graph(
                            "booster.tank_pressure_lox[0], booster.tank_pressure_rp1[0], booster.inlet_pressure_lox[0], booster.inlet_pressure_rp1[0]",
                            name="Tank + inlet pressures (Pa)",
                            colors=[
                                "cyan",
                                "orange",
                                "blue",
                                "red",
                            ],
                        ),
                    ),
                    ui.hsplit(
                        ui.graph(
                            "booster.propellant_lox[0], booster.propellant_rp1[0]",
                            name="Propellant (kg)",
                            colors=[
                                "cyan",
                                "orange",
                            ],
                        ),
                        ui.graph(
                            "booster.nitrogen_kg[0]",
                            name="RCS nitrogen (kg)",
                            colors=[
                                "white",
                            ],
                        ),
                    ),
                    share=0.28,
                ),
                share=0.75,
            ),
            ui.hsplit(
                ui.graph(
                    "booster.fsw_phase[0]",
                    name="Mission phase (0..11)",
                    colors=[
                        "yellow",
                    ],
                ),
                ui.graph(
                    "booster.thrust_total[0]",
                    name="Cluster thrust (N)",
                    colors=[
                        "orange",
                    ],
                ),
                ui.graph(
                    "booster.qbar[0]",
                    name="Dynamic pressure (Pa)",
                    colors=[
                        "red",
                    ],
                ),
                ui.graph(
                    "booster.fin_state",
                    name="Grid fins (rad)",
                ),
                ui.graph(
                    "booster.rcs_levels",
                    name="RCS thrusters (8)",
                ),
                ui.graph(
                    "booster.engine_spool",
                    name="Engine spool (%)",
                ),
                ui.graph(
                    "booster.tvc_state",
                    name="TVC gimbal (rad)",
                ),
                share=0.25,
            ),
        ),
        ui.object_3d(
            "booster.visual_pos",
            mesh=ui.glb(
                "falcon9.glb",
                scale=0.9944,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, -90.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="absolute",
            icon=ui.icon(
                builtin="rocket_launch",
                color=ui.color(
                    70,
                    130,
                    240,
                    255,
                ),
                size=32.0,
            ),
            thrusters=[
                ui.thruster(
                    name="merlin",
                    body_frame=True,
                    position=(-1.2, 0.0, 0.0),
                    intensity="booster.plume_viz",
                    effect="effects/falcon9/merlin_core.effect",
                    cutoff=0.02,
                    scale=1.0,
                    light=ui.thruster_light(
                        color=(1.0, 0.83, 0.58),
                        intensity=30000000.0,
                        range=120.0,
                        offset=6.0,
                        shadows=False,
                    ),
                    extra_effects=[
                        "effects/falcon9/merlin_flame.effect",
                    ],
                ),
                ui.thruster(
                    name="exhaust_smoke",
                    body_frame=True,
                    position=(-8.0, 0.0, 0.0),
                    direction=(-1.0, 0.0, 0.0),
                    intensity="booster.smoke_viz[0]",
                    effect="effects/falcon9/exhaust_smoke.effect",
                    cutoff=0.01,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_0",
                    body_frame=True,
                    position=(46.0, 1.83, 0.0),
                    direction=(0.0, 0.0, -1.0),
                    intensity="booster.rcs_levels[0]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_1",
                    body_frame=True,
                    position=(46.0, 1.83, 0.0),
                    direction=(0.0, 0.0, 1.0),
                    intensity="booster.rcs_levels[1]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_2",
                    body_frame=True,
                    position=(46.0, -1.83, 0.0),
                    direction=(0.0, 0.0, -1.0),
                    intensity="booster.rcs_levels[2]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_3",
                    body_frame=True,
                    position=(46.0, -1.83, 0.0),
                    direction=(0.0, 0.0, 1.0),
                    intensity="booster.rcs_levels[3]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_4",
                    body_frame=True,
                    position=(46.0, 1.83, 0.0),
                    direction=(0.0, -1.0, 0.0),
                    intensity="booster.rcs_levels[4]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_5",
                    body_frame=True,
                    position=(46.0, 1.83, 0.0),
                    direction=(0.0, 1.0, 0.0),
                    intensity="booster.rcs_levels[5]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_6",
                    body_frame=True,
                    position=(46.0, -1.83, 0.0),
                    direction=(0.0, 1.0, 0.0),
                    intensity="booster.rcs_levels[6]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
                ui.thruster(
                    name="rcs_7",
                    body_frame=True,
                    position=(46.0, -1.83, 0.0),
                    direction=(0.0, -1.0, 0.0),
                    intensity="booster.rcs_levels[7]",
                    effect="effects/falcon9/rcs_dart.effect",
                    cutoff=0.003,
                    scale=1.0,
                ),
            ],
        ),
        ui.object_3d(
            "pad.world_pos",
            mesh=ui.sphere(
                radius=0.02,
                color="white",
                emissivity=0.0,
            ),
            orientation="absolute",
            thrusters=[
                ui.thruster(
                    name="pad_smoke",
                    body_frame=True,
                    position=(0.0, 2.0, 0.0),
                    direction=(0.0, -1.0, 0.0),
                    intensity="booster.pad_smoke_viz[0]",
                    effect="effects/falcon9/pad_smoke.effect",
                    cutoff=0.01,
                    scale=1.0,
                ),
            ],
        ),
        ui.object_3d(
            "lz1.world_pos",
            mesh=ui.glb(
                "spacex_drone_barge.glb",
                scale=1.0,
                translate=(0.0, 0.0, 0.0),
                rotate=(0.0, 0.0, 0.0),
                emissivity=0.0,
                glow=0.0,
            ),
            orientation="absolute",
            thrusters=[
                ui.thruster(
                    name="lz1_smoke",
                    body_frame=True,
                    position=(0.0, 2.0, 0.0),
                    direction=(0.0, -1.0, 0.0),
                    intensity="booster.landing_smoke_viz[0]",
                    effect="effects/falcon9/pad_smoke.effect",
                    cutoff=0.01,
                    scale=1.0,
                ),
            ],
        ),
        ui.object_3d(
            "booster_truth.world_pos",
            mesh=ui.sphere(
                radius=0.5,
                color=ui.color(
                    60,
                    200,
                    90,
                    160,
                ),
                emissivity=0.0,
            ),
            orientation="relative",
            icon=ui.icon(
                builtin="my_location",
                color=ui.color(
                    60,
                    200,
                    90,
                    255,
                ),
                size=24.0,
            ),
        ),
        ui.line_3d(
            "booster.world_pos",
            line_width=2.0,
            color=ui.color(
                70,
                130,
                240,
                200,
            ),
            perspective=False,
        ),
        ui.line_3d(
            "booster_truth.world_pos",
            line_width=2.0,
            color=ui.color(
                60,
                200,
                90,
                160,
            ),
            perspective=False,
        ),
        coordinate=ui.coordinate(
            frame="ECEF",
        ),
        timeline=ui.timeline(
            played_color="yalk",
            future_color="white",
            follow_latest=True,
            range="last_30s",
        ),
        environment=ui.environment(
            sun=ui.sun(
                illuminance=100000.0,
                shadows=True,
            ),
            ambient=0.05,
            earth=ui.earth(
                stars_density=0.05,
                stars_size=0.4,
                stars_brightness=1.88,
                city_lights_density=0.05,
                city_lights_size=1.0,
                city_lights_height=0.0,
                city_lights_brightness=0.05,
                airglow_density=0.55,
                airglow_size=1.05,
                airglow_brightness=1.45,
                night_map_brightness=0.05,
            ),
        ),
        telemetry_mode=True,
    )


if __name__ == "__main__":
    print(build().emit_kdl())
